#!/bin/sh
# Copyright (c) 2015-2025 The Decred developers
# Use of this source code is governed by an ISC
# license that can be found in the LICENSE file.

set -e

CERT_DIR="/app-data/dcrd"
RPC_CERT="${CERT_DIR}/rpc.cert"
RPC_KEY="${CERT_DIR}/rpc.key"

mkdir -p "${CERT_DIR}"

if [ ! -f "${RPC_CERT}" ] || [ ! -f "${RPC_KEY}" ]; then
    echo "Generating TLS certificates..."
    
    if certgen --help 2>&1 | grep -q "dcrd"; then
        certgen --host=dcrd \
                --host=dcrwallet \
                --host=localhost \
                --host=127.0.0.1 \
                --host=0.0.0.0 \
                --host=$(hostname) \
                --directory="${CERT_DIR}" \
                --org="dcrd autogenerated cert" \
                --duration=8760h
    else
        openssl req -x509 -nodes -newkey rsa:2048 \
                -keyout "${RPC_KEY}" \
                -out "${RPC_CERT}" \
                -days 365 \
                -subj "/O=dcrd autogenerated cert" \
                -addext "subjectAltName=DNS:dcrd,DNS:dcrwallet,DNS:localhost,IP:127.0.0.1"
    fi
    
    echo "✓ TLS certificates generated: ${CERT_DIR}"
else
    echo "✓ Using existing TLS certificates"
fi

if [ -n "$DCRD_EXTRA_ARGS" ]; then
    # shellcheck disable=SC2086
    exec dcrd --appdata=/app-data/dcrd "$@" $DCRD_EXTRA_ARGS
else
    exec dcrd --appdata=/app-data/dcrd "$@"
fi

