#!/bin/sh
# Copyright (c) 2015-2026 The Decred developers
# Use of this source code is governed by an ISC
# license that can be found in the LICENSE file.

set -e

CERT_DIR="/app-data/dcrd"
RPC_CERT="${CERT_DIR}/rpc.cert"
RPC_KEY="${CERT_DIR}/rpc.key"

mkdir -p "${CERT_DIR}"

if [ ! -f "${RPC_CERT}" ] || [ ! -f "${RPC_KEY}" ]; then
    echo "Generating TLS certificates..."

    if certgen --help 2>&1 | grep -q "dcrd"; then
        certgen --host=dcrd \
                --host=dcrwallet \
                --host=localhost \
                --host=127.0.0.1 \
                --host=0.0.0.0 \
                --host=$(hostname) \
                --directory="${CERT_DIR}" \
                --org="dcrd autogenerated cert" \
                --duration=8760h
    else
        openssl req -x509 -nodes -newkey rsa:2048 \
                -keyout "${RPC_KEY}" \
                -out "${RPC_CERT}" \
                -days 365 \
                -subj "/O=dcrd autogenerated cert" \
                -addext "subjectAltName=DNS:dcrd,DNS:dcrwallet,DNS:localhost,IP:127.0.0.1"
    fi

    echo "✓ TLS certificates generated: ${CERT_DIR}"
else
    echo "✓ Using existing TLS certificates"
fi

# dcrd is wallet-agnostic, so this supervisor watches only the shared Tor
# pointer the dashboard writes and relaunches dcrd when the toggle changes.
# The container stays up; only the inner dcrd process cycles. The pointer is
# parsed with sed (the image has no jq); proxy endpoint comes from env, the
# on/off decision from the pointer (absent pointer means Tor disabled).
set +e

TOR_POINTER="/app-data/control/tor.json"
CHILD_PID=""
RUNNING_TOR_REV="__none__"

tor_field() {
    [ -f "${TOR_POINTER}" ] || { echo "$2"; return; }
    v=$(sed -n "s/.*\"$1\"[[:space:]]*:[[:space:]]*\"\{0,1\}\([A-Za-z0-9]*\).*/\1/p" "${TOR_POINTER}" | head -1)
    [ -n "${v}" ] && echo "${v}" || echo "$2"
}

build_tor_args() {
    TOR_ARGS=""
    [ "$(tor_field enabled false)" = "true" ] || return
    [ -n "${TOR_PROXY_IP}" ] && [ -n "${TOR_PROXY_PORT}" ] || return
    TOR_ARGS="--proxy=${TOR_PROXY_IP}:${TOR_PROXY_PORT}"
    [ "$(tor_field isolation true)" = "true" ] && TOR_ARGS="${TOR_ARGS} --torisolation"
    if [ "$(tor_field dcrdOnion false)" = "true" ] && [ -f /tor-data/dcrd-hs/hostname ]; then
        host=$(cat /tor-data/dcrd-hs/hostname 2>/dev/null)
        [ -n "${host}" ] && TOR_ARGS="${TOR_ARGS} --externalip=${host}:9108"
    fi
}

stop_child() {
    [ -z "${CHILD_PID}" ] && return
    kill -INT "${CHILD_PID}" 2>/dev/null
    i=0
    while kill -0 "${CHILD_PID}" 2>/dev/null; do
        i=$((i + 1))
        if [ "${i}" -ge 30 ]; then
            kill -KILL "${CHILD_PID}" 2>/dev/null
            break
        fi
        sleep 1
    done
    wait "${CHILD_PID}" 2>/dev/null
    CHILD_PID=""
}

start_dcrd() {
    build_tor_args
    if [ -n "${TOR_ARGS}" ]; then
        echo "Starting dcrd over Tor (${TOR_ARGS})"
    else
        echo "Starting dcrd on clearnet"
    fi
    # shellcheck disable=SC2086
    dcrd --appdata=/app-data/dcrd "$@" ${DCRD_EXTRA_ARGS} ${TOR_ARGS} &
    CHILD_PID=$!
}

shutdown() {
    stop_child
    exit 0
}
trap shutdown INT TERM

while true; do
    TOR_REV=$(tor_field rev 0)

    if [ -n "${CHILD_PID}" ] && ! kill -0 "${CHILD_PID}" 2>/dev/null; then
        wait "${CHILD_PID}" 2>/dev/null
        CHILD_PID=""
        RUNNING_TOR_REV="__none__"
    fi

    if [ "${TOR_REV}" != "${RUNNING_TOR_REV}" ] || [ -z "${CHILD_PID}" ]; then
        if [ -n "${CHILD_PID}" ]; then
            echo "Applying Tor change (rev ${TOR_REV})"
            stop_child
        fi
        start_dcrd "$@"
        RUNNING_TOR_REV="${TOR_REV}"
    fi

    sleep 2
done
