// Copyright (c) 2015-2026 The Decred developers
// Use of this source code is governed by an ISC
// license that can be found in the LICENSE file.

// Curated set of classic unicode emojis for the chat composer. Keywords drive
// the picker's search filter. Deliberately limited to broadly useful faces,
// gestures, hearts, common objects, and symbols; no skin-tone variants.

export interface ChatEmoji {
  char: string;
  keywords: string;
}

export interface EmojiCategory {
  name: string;
  emojis: ChatEmoji[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    name: 'Smileys',
    emojis: [
      { char: '😀', keywords: 'grin happy smile face' },
      { char: '😃', keywords: 'happy smile joy face' },
      { char: '😄', keywords: 'happy smile laugh face' },
      { char: '😁', keywords: 'grin beam happy face' },
      { char: '😆', keywords: 'laugh haha happy face' },
      { char: '😅', keywords: 'sweat nervous laugh face' },
      { char: '😂', keywords: 'laugh cry tears joy lol' },
      { char: '🤣', keywords: 'rofl laugh rolling lol' },
      { char: '😊', keywords: 'smile blush happy face' },
      { char: '🙂', keywords: 'smile slight face' },
      { char: '🙃', keywords: 'upside down silly face' },
      { char: '😉', keywords: 'wink flirt face' },
      { char: '😌', keywords: 'relieved calm face' },
      { char: '😍', keywords: 'love heart eyes adore' },
      { char: '🥰', keywords: 'love hearts adore face' },
      { char: '😘', keywords: 'kiss blow love face' },
      { char: '😗', keywords: 'kiss face' },
      { char: '😙', keywords: 'kiss smile face' },
      { char: '😋', keywords: 'yum tasty tongue face' },
      { char: '😛', keywords: 'tongue playful face' },
      { char: '😜', keywords: 'tongue wink silly face' },
      { char: '🤪', keywords: 'crazy zany silly face' },
      { char: '😝', keywords: 'tongue squint face' },
      { char: '🤑', keywords: 'money mouth rich face' },
      { char: '🤗', keywords: 'hug hands face' },
      { char: '🤭', keywords: 'oops giggle hand face' },
      { char: '🤫', keywords: 'shush quiet secret face' },
      { char: '🤔', keywords: 'think hmm thinking face' },
      { char: '🤐', keywords: 'zip mouth quiet face' },
      { char: '🤨', keywords: 'raised eyebrow skeptical face' },
      { char: '😐', keywords: 'neutral meh face' },
      { char: '😑', keywords: 'expressionless meh face' },
      { char: '😶', keywords: 'no mouth blank face' },
      { char: '😏', keywords: 'smirk sly face' },
      { char: '😒', keywords: 'unamused meh face' },
      { char: '🙄', keywords: 'eye roll annoyed face' },
      { char: '😬', keywords: 'grimace awkward face' },
      { char: '😮‍💨', keywords: 'exhale sigh relief face' },
      { char: '🤥', keywords: 'lying liar nose face' },
      { char: '😴', keywords: 'sleep zzz tired face' },
      { char: '😪', keywords: 'sleepy tired face' },
      { char: '😌', keywords: 'relieved content face' },
      { char: '😔', keywords: 'sad pensive down face' },
      { char: '😕', keywords: 'confused unsure face' },
      { char: '🙁', keywords: 'frown sad face' },
      { char: '😟', keywords: 'worried sad face' },
      { char: '😣', keywords: 'persevere struggle face' },
      { char: '😞', keywords: 'disappointed sad face' },
      { char: '😩', keywords: 'weary tired face' },
      { char: '😫', keywords: 'tired exhausted face' },
      { char: '🥺', keywords: 'pleading puppy eyes beg face' },
      { char: '😢', keywords: 'cry sad tear face' },
      { char: '😭', keywords: 'sob cry bawl face' },
      { char: '😤', keywords: 'huff angry steam face' },
      { char: '😠', keywords: 'angry mad face' },
      { char: '😡', keywords: 'rage furious mad face' },
      { char: '🤬', keywords: 'swear curse angry face' },
      { char: '🤯', keywords: 'mind blown shock face' },
      { char: '😳', keywords: 'flushed embarrassed face' },
      { char: '🥵', keywords: 'hot sweat heat face' },
      { char: '🥶', keywords: 'cold freezing face' },
      { char: '😱', keywords: 'scream shock fear face' },
      { char: '😨', keywords: 'fearful scared face' },
      { char: '😰', keywords: 'anxious sweat nervous face' },
      { char: '😥', keywords: 'sad relieved sweat face' },
      { char: '😓', keywords: 'sweat tired face' },
      { char: '🤗', keywords: 'hug face' },
      { char: '🤩', keywords: 'star struck excited wow face' },
      { char: '🥳', keywords: 'party celebrate hat face' },
      { char: '😎', keywords: 'cool sunglasses face' },
      { char: '🤓', keywords: 'nerd glasses geek face' },
      { char: '🧐', keywords: 'monocle inspect face' },
      { char: '😇', keywords: 'angel halo innocent face' },
      { char: '🤠', keywords: 'cowboy hat face' },
      { char: '🥱', keywords: 'yawn bored tired face' },
      { char: '😷', keywords: 'mask sick face' },
      { char: '🤒', keywords: 'sick thermometer face' },
      { char: '🤕', keywords: 'hurt bandage injured face' },
      { char: '🤢', keywords: 'sick nausea face' },
      { char: '🤮', keywords: 'vomit sick face' },
      { char: '🤧', keywords: 'sneeze sick tissue face' },
      { char: '😵', keywords: 'dizzy faint face' },
      { char: '🤡', keywords: 'clown face' },
      { char: '💩', keywords: 'poop crap face' },
      { char: '👻', keywords: 'ghost boo spooky' },
      { char: '💀', keywords: 'skull dead' },
      { char: '👽', keywords: 'alien ufo' },
      { char: '🤖', keywords: 'robot bot' },
    ],
  },
  {
    name: 'Gestures',
    emojis: [
      { char: '👍', keywords: 'thumbs up like yes good' },
      { char: '👎', keywords: 'thumbs down dislike no bad' },
      { char: '👌', keywords: 'ok perfect hand' },
      { char: '🤌', keywords: 'pinch italian hand' },
      { char: '✌️', keywords: 'peace victory hand' },
      { char: '🤞', keywords: 'fingers crossed luck hand' },
      { char: '🤟', keywords: 'love you hand' },
      { char: '🤘', keywords: 'rock horns hand' },
      { char: '🤙', keywords: 'call me shaka hand' },
      { char: '👈', keywords: 'point left hand' },
      { char: '👉', keywords: 'point right hand' },
      { char: '👆', keywords: 'point up hand' },
      { char: '👇', keywords: 'point down hand' },
      { char: '☝️', keywords: 'point up one hand' },
      { char: '✋', keywords: 'stop high five hand' },
      { char: '🤚', keywords: 'back hand raised' },
      { char: '🖐️', keywords: 'hand fingers splayed' },
      { char: '🖖', keywords: 'vulcan spock hand' },
      { char: '👋', keywords: 'wave hello bye hand' },
      { char: '🤝', keywords: 'handshake deal agree' },
      { char: '👏', keywords: 'clap applause hands' },
      { char: '🙌', keywords: 'raise hands celebrate praise' },
      { char: '🙏', keywords: 'pray thanks please hands' },
      { char: '👊', keywords: 'fist bump punch' },
      { char: '✊', keywords: 'fist raised power' },
      { char: '🤛', keywords: 'fist left bump' },
      { char: '🤜', keywords: 'fist right bump' },
      { char: '💪', keywords: 'muscle strong flex arm' },
      { char: '🫶', keywords: 'heart hands love' },
      { char: '👐', keywords: 'open hands' },
      { char: '🤲', keywords: 'palms up hands' },
      { char: '🫰', keywords: 'finger heart hand' },
    ],
  },
  {
    name: 'Hearts',
    emojis: [
      { char: '❤️', keywords: 'red heart love' },
      { char: '🧡', keywords: 'orange heart love' },
      { char: '💛', keywords: 'yellow heart love' },
      { char: '💚', keywords: 'green heart love' },
      { char: '💙', keywords: 'blue heart love' },
      { char: '💜', keywords: 'purple heart love' },
      { char: '🖤', keywords: 'black heart love' },
      { char: '🤍', keywords: 'white heart love' },
      { char: '🤎', keywords: 'brown heart love' },
      { char: '💗', keywords: 'growing heart love' },
      { char: '💓', keywords: 'beating heart love' },
      { char: '💞', keywords: 'revolving hearts love' },
      { char: '💕', keywords: 'two hearts love' },
      { char: '💘', keywords: 'heart arrow cupid love' },
      { char: '💝', keywords: 'heart gift love' },
      { char: '💔', keywords: 'broken heart sad' },
      { char: '❣️', keywords: 'heart exclamation love' },
      { char: '💟', keywords: 'heart decoration love' },
    ],
  },
  {
    name: 'Objects',
    emojis: [
      { char: '🔥', keywords: 'fire lit hot flame' },
      { char: '⭐', keywords: 'star favorite' },
      { char: '🌟', keywords: 'glowing star sparkle' },
      { char: '✨', keywords: 'sparkles shiny magic' },
      { char: '⚡', keywords: 'lightning bolt zap fast' },
      { char: '💥', keywords: 'boom explosion collision' },
      { char: '💫', keywords: 'dizzy star sparkle' },
      { char: '🎉', keywords: 'party tada celebrate' },
      { char: '🎊', keywords: 'confetti party celebrate' },
      { char: '🎈', keywords: 'balloon party' },
      { char: '🎁', keywords: 'gift present box' },
      { char: '🏆', keywords: 'trophy win award' },
      { char: '🥇', keywords: 'gold medal first win' },
      { char: '🎯', keywords: 'target bullseye dart goal' },
      { char: '💡', keywords: 'idea bulb light' },
      { char: '💰', keywords: 'money bag cash' },
      { char: '💵', keywords: 'dollar money cash' },
      { char: '💸', keywords: 'money wings spend cash' },
      { char: '💎', keywords: 'diamond gem jewel' },
      { char: '🔑', keywords: 'key unlock' },
      { char: '🔒', keywords: 'lock secure closed' },
      { char: '📈', keywords: 'chart up growth gain' },
      { char: '📉', keywords: 'chart down loss drop' },
      { char: '🚀', keywords: 'rocket launch moon fast' },
      { char: '⏰', keywords: 'alarm clock time' },
      { char: '⌛', keywords: 'hourglass time wait' },
      { char: '☕', keywords: 'coffee tea drink' },
      { char: '🍺', keywords: 'beer drink cheers' },
      { char: '🍻', keywords: 'beers cheers drink' },
      { char: '🍕', keywords: 'pizza food' },
      { char: '🎂', keywords: 'cake birthday' },
      { char: '🍀', keywords: 'clover luck' },
      { char: '🌈', keywords: 'rainbow' },
      { char: '☀️', keywords: 'sun sunny weather' },
      { char: '🌙', keywords: 'moon night' },
      { char: '💤', keywords: 'sleep zzz' },
      { char: '🎵', keywords: 'music note song' },
      { char: '🎶', keywords: 'music notes song' },
      { char: '📌', keywords: 'pin pushpin' },
      { char: '📎', keywords: 'paperclip attach' },
    ],
  },
  {
    name: 'Symbols',
    emojis: [
      { char: '✅', keywords: 'check yes done correct tick' },
      { char: '❌', keywords: 'cross no wrong x' },
      { char: '❎', keywords: 'cross mark button no' },
      { char: '⭕', keywords: 'circle o correct' },
      { char: '❓', keywords: 'question mark' },
      { char: '❗', keywords: 'exclamation important' },
      { char: '‼️', keywords: 'double exclamation' },
      { char: '⚠️', keywords: 'warning caution alert' },
      { char: '🚫', keywords: 'no forbidden ban stop' },
      { char: '💯', keywords: 'hundred perfect score' },
      { char: '🔝', keywords: 'top up arrow' },
      { char: '🆗', keywords: 'ok button' },
      { char: '🆕', keywords: 'new button' },
      { char: '🔁', keywords: 'repeat loop' },
      { char: '➡️', keywords: 'arrow right' },
      { char: '⬅️', keywords: 'arrow left' },
      { char: '⬆️', keywords: 'arrow up' },
      { char: '⬇️', keywords: 'arrow down' },
      { char: '➕', keywords: 'plus add' },
      { char: '➖', keywords: 'minus subtract' },
      { char: '✔️', keywords: 'check tick yes' },
      { char: '☑️', keywords: 'check box ticked' },
      { char: '🔔', keywords: 'bell notification' },
      { char: '🔕', keywords: 'bell off mute' },
      { char: '♻️', keywords: 'recycle' },
      { char: '🆘', keywords: 'sos help' },
      { char: '🔴', keywords: 'red circle dot' },
      { char: '🟢', keywords: 'green circle dot' },
      { char: '🟡', keywords: 'yellow circle dot' },
      { char: '🔵', keywords: 'blue circle dot' },
    ],
  },
];
