// The game <-> dcrpulse gaming bridge contract.
//
// The game is the gRPC CLIENT and dials the bridge over mTLS on a dedicated
// port. Its identity is NEVER a field in any message: it is the client
// certificate, resolved by the bridge from the verified peer. A game therefore
// cannot assert which game it is - it presents a credential and the bridge
// decides. One Subscribe stream carries every bridge->game push; everything the
// game initiates is a unary call. The bridge never dials the game, so a game
// behind NAT needs no inbound port.
//
// The bridge forms an opinion only on the money verbs and on routing. Frame
// contents are opaque: what a frame means is between the players, who sign
// their own traffic and check each other's, and a bridge that inspected
// payloads would be adding a party nobody agreed to trust.
//
// This file is the contract. A game generates its own client from it; there is
// no shared Go package, because the module path here is not fetchable. Changing
// it is changing a published wire format - see contract_test.go.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.1
// source: gaming_bridge.proto

package gamingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BridgeService_Hello_FullMethodName        = "/dcrpulse.gaming.v1.BridgeService/Hello"
	BridgeService_Subscribe_FullMethodName    = "/dcrpulse.gaming.v1.BridgeService/Subscribe"
	BridgeService_Respond_FullMethodName      = "/dcrpulse.gaming.v1.BridgeService/Respond"
	BridgeService_ReportState_FullMethodName  = "/dcrpulse.gaming.v1.BridgeService/ReportState"
	BridgeService_RequestSpend_FullMethodName = "/dcrpulse.gaming.v1.BridgeService/RequestSpend"
	BridgeService_SpendStatus_FullMethodName  = "/dcrpulse.gaming.v1.BridgeService/SpendStatus"
	BridgeService_Broadcast_FullMethodName    = "/dcrpulse.gaming.v1.BridgeService/Broadcast"
	BridgeService_SendFrame_FullMethodName    = "/dcrpulse.gaming.v1.BridgeService/SendFrame"
	BridgeService_ChainTip_FullMethodName     = "/dcrpulse.gaming.v1.BridgeService/ChainTip"
	BridgeService_BlockHash_FullMethodName    = "/dcrpulse.gaming.v1.BridgeService/BlockHash"
	BridgeService_Outpoint_FullMethodName     = "/dcrpulse.gaming.v1.BridgeService/Outpoint"
)

// BridgeServiceClient is the client API for BridgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BridgeService is served by dcrpulse on its dedicated mTLS gaming port.
type BridgeServiceClient interface {
	// Hello is called once, before Subscribe. It is where the two sides agree
	// about who and what they are before anything can go wrong quietly.
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// Subscribe is the single stream the game opens; the bridge pushes every
	// event down it. Closing it - by revocation, by the bridge going off, or by
	// the game leaving - ends that game's participation.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BridgeEvent], error)
	// Respond answers one BridgeRequest. The bridge checks that the credential
	// on this call resolves to the game the request was addressed to.
	Respond(ctx context.Context, in *RespondRequest, opts ...grpc.CallOption) (*RespondReply, error)
	// ReportState is what the console shows. It is sent unsolicited when
	// something moves, and the bridge keeps the last one - so a game that is not
	// running renders as it last was rather than as an error.
	ReportState(ctx context.Context, in *GameState, opts ...grpc.CallOption) (*ReportStateReply, error)
	// RequestSpend records a request to pay money IN. It never spends: this
	// process holds no wallet passphrase, so all it can do is ask a person.
	// Checked against the calling game's own caps and account.
	//
	// NON-IDEMPOTENT. It must never be placed in a gRPC retry policy: a
	// transparent retry would ask for the same stake twice.
	RequestSpend(ctx context.Context, in *RequestSpendRequest, opts ...grpc.CallOption) (*Spend, error)
	// SpendStatus reports what became of one of THIS game's requests.
	//
	// Polling is the answer of record, not the SpendSettled push. Not being able
	// to ask is not the same as the answer being no, and only a call the game
	// makes itself can tell those apart.
	SpendStatus(ctx context.Context, in *SpendStatusRequest, opts ...grpc.CallOption) (*Spend, error)
	// Broadcast relays a transaction the game signed itself - a matured bond, a
	// stake past its timelock, a settlement every member signed. Bounded by
	// shape rather than by intent: every input spends game money the wallet does
	// not own, and unless every input required more than one signature, every
	// output pays an address the wallet does.
	Broadcast(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (*BroadcastReply, error)
	// SendFrame sends one opaque protocol frame to a table's group chat. The
	// bridge checks only that the frame is the calling game's own.
	SendFrame(ctx context.Context, in *SendFrameRequest, opts ...grpc.CallOption) (*SendFrameReply, error)
	// The facts a game needs to agree deadlines and check its peers' bonds. A
	// height is something every player can verify; a clock is each machine's
	// opinion and nobody can be shown to have read it wrong.
	ChainTip(ctx context.Context, in *ChainTipRequest, opts ...grpc.CallOption) (*ChainTipReply, error)
	BlockHash(ctx context.Context, in *BlockHashRequest, opts ...grpc.CallOption) (*BlockHashReply, error)
	Outpoint(ctx context.Context, in *OutpointRequest, opts ...grpc.CallOption) (*OutpointReply, error)
}

type bridgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBridgeServiceClient(cc grpc.ClientConnInterface) BridgeServiceClient {
	return &bridgeServiceClient{cc}
}

func (c *bridgeServiceClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, BridgeService_Hello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BridgeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BridgeService_ServiceDesc.Streams[0], BridgeService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, BridgeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BridgeService_SubscribeClient = grpc.ServerStreamingClient[BridgeEvent]

func (c *bridgeServiceClient) Respond(ctx context.Context, in *RespondRequest, opts ...grpc.CallOption) (*RespondReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespondReply)
	err := c.cc.Invoke(ctx, BridgeService_Respond_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) ReportState(ctx context.Context, in *GameState, opts ...grpc.CallOption) (*ReportStateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportStateReply)
	err := c.cc.Invoke(ctx, BridgeService_ReportState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) RequestSpend(ctx context.Context, in *RequestSpendRequest, opts ...grpc.CallOption) (*Spend, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Spend)
	err := c.cc.Invoke(ctx, BridgeService_RequestSpend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) SpendStatus(ctx context.Context, in *SpendStatusRequest, opts ...grpc.CallOption) (*Spend, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Spend)
	err := c.cc.Invoke(ctx, BridgeService_SpendStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) Broadcast(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (*BroadcastReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BroadcastReply)
	err := c.cc.Invoke(ctx, BridgeService_Broadcast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) SendFrame(ctx context.Context, in *SendFrameRequest, opts ...grpc.CallOption) (*SendFrameReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendFrameReply)
	err := c.cc.Invoke(ctx, BridgeService_SendFrame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) ChainTip(ctx context.Context, in *ChainTipRequest, opts ...grpc.CallOption) (*ChainTipReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChainTipReply)
	err := c.cc.Invoke(ctx, BridgeService_ChainTip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) BlockHash(ctx context.Context, in *BlockHashRequest, opts ...grpc.CallOption) (*BlockHashReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockHashReply)
	err := c.cc.Invoke(ctx, BridgeService_BlockHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) Outpoint(ctx context.Context, in *OutpointRequest, opts ...grpc.CallOption) (*OutpointReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OutpointReply)
	err := c.cc.Invoke(ctx, BridgeService_Outpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BridgeServiceServer is the server API for BridgeService service.
// All implementations must embed UnimplementedBridgeServiceServer
// for forward compatibility.
//
// BridgeService is served by dcrpulse on its dedicated mTLS gaming port.
type BridgeServiceServer interface {
	// Hello is called once, before Subscribe. It is where the two sides agree
	// about who and what they are before anything can go wrong quietly.
	Hello(context.Context, *HelloRequest) (*HelloReply, error)
	// Subscribe is the single stream the game opens; the bridge pushes every
	// event down it. Closing it - by revocation, by the bridge going off, or by
	// the game leaving - ends that game's participation.
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[BridgeEvent]) error
	// Respond answers one BridgeRequest. The bridge checks that the credential
	// on this call resolves to the game the request was addressed to.
	Respond(context.Context, *RespondRequest) (*RespondReply, error)
	// ReportState is what the console shows. It is sent unsolicited when
	// something moves, and the bridge keeps the last one - so a game that is not
	// running renders as it last was rather than as an error.
	ReportState(context.Context, *GameState) (*ReportStateReply, error)
	// RequestSpend records a request to pay money IN. It never spends: this
	// process holds no wallet passphrase, so all it can do is ask a person.
	// Checked against the calling game's own caps and account.
	//
	// NON-IDEMPOTENT. It must never be placed in a gRPC retry policy: a
	// transparent retry would ask for the same stake twice.
	RequestSpend(context.Context, *RequestSpendRequest) (*Spend, error)
	// SpendStatus reports what became of one of THIS game's requests.
	//
	// Polling is the answer of record, not the SpendSettled push. Not being able
	// to ask is not the same as the answer being no, and only a call the game
	// makes itself can tell those apart.
	SpendStatus(context.Context, *SpendStatusRequest) (*Spend, error)
	// Broadcast relays a transaction the game signed itself - a matured bond, a
	// stake past its timelock, a settlement every member signed. Bounded by
	// shape rather than by intent: every input spends game money the wallet does
	// not own, and unless every input required more than one signature, every
	// output pays an address the wallet does.
	Broadcast(context.Context, *BroadcastRequest) (*BroadcastReply, error)
	// SendFrame sends one opaque protocol frame to a table's group chat. The
	// bridge checks only that the frame is the calling game's own.
	SendFrame(context.Context, *SendFrameRequest) (*SendFrameReply, error)
	// The facts a game needs to agree deadlines and check its peers' bonds. A
	// height is something every player can verify; a clock is each machine's
	// opinion and nobody can be shown to have read it wrong.
	ChainTip(context.Context, *ChainTipRequest) (*ChainTipReply, error)
	BlockHash(context.Context, *BlockHashRequest) (*BlockHashReply, error)
	Outpoint(context.Context, *OutpointRequest) (*OutpointReply, error)
	mustEmbedUnimplementedBridgeServiceServer()
}

// UnimplementedBridgeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBridgeServiceServer struct{}

func (UnimplementedBridgeServiceServer) Hello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedBridgeServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[BridgeEvent]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedBridgeServiceServer) Respond(context.Context, *RespondRequest) (*RespondReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Respond not implemented")
}
func (UnimplementedBridgeServiceServer) ReportState(context.Context, *GameState) (*ReportStateReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportState not implemented")
}
func (UnimplementedBridgeServiceServer) RequestSpend(context.Context, *RequestSpendRequest) (*Spend, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestSpend not implemented")
}
func (UnimplementedBridgeServiceServer) SpendStatus(context.Context, *SpendStatusRequest) (*Spend, error) {
	return nil, status.Error(codes.Unimplemented, "method SpendStatus not implemented")
}
func (UnimplementedBridgeServiceServer) Broadcast(context.Context, *BroadcastRequest) (*BroadcastReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Broadcast not implemented")
}
func (UnimplementedBridgeServiceServer) SendFrame(context.Context, *SendFrameRequest) (*SendFrameReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SendFrame not implemented")
}
func (UnimplementedBridgeServiceServer) ChainTip(context.Context, *ChainTipRequest) (*ChainTipReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ChainTip not implemented")
}
func (UnimplementedBridgeServiceServer) BlockHash(context.Context, *BlockHashRequest) (*BlockHashReply, error) {
	return nil, status.Error(codes.Unimplemented, "method BlockHash not implemented")
}
func (UnimplementedBridgeServiceServer) Outpoint(context.Context, *OutpointRequest) (*OutpointReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Outpoint not implemented")
}
func (UnimplementedBridgeServiceServer) mustEmbedUnimplementedBridgeServiceServer() {}
func (UnimplementedBridgeServiceServer) testEmbeddedByValue()                       {}

// UnsafeBridgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BridgeServiceServer will
// result in compilation errors.
type UnsafeBridgeServiceServer interface {
	mustEmbedUnimplementedBridgeServiceServer()
}

func RegisterBridgeServiceServer(s grpc.ServiceRegistrar, srv BridgeServiceServer) {
	// If the following call panics, it indicates UnimplementedBridgeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BridgeService_ServiceDesc, srv)
}

func _BridgeService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BridgeServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, BridgeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BridgeService_SubscribeServer = grpc.ServerStreamingServer[BridgeEvent]

func _BridgeService_Respond_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RespondRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).Respond(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_Respond_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).Respond(ctx, req.(*RespondRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_ReportState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).ReportState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_ReportState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).ReportState(ctx, req.(*GameState))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_RequestSpend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestSpendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).RequestSpend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_RequestSpend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).RequestSpend(ctx, req.(*RequestSpendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_SpendStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpendStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).SpendStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_SpendStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).SpendStatus(ctx, req.(*SpendStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_Broadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).Broadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_Broadcast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).Broadcast(ctx, req.(*BroadcastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_SendFrame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendFrameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).SendFrame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_SendFrame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).SendFrame(ctx, req.(*SendFrameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_ChainTip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainTipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).ChainTip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_ChainTip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).ChainTip(ctx, req.(*ChainTipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_BlockHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).BlockHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_BlockHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).BlockHash(ctx, req.(*BlockHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_Outpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OutpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).Outpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_Outpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).Outpoint(ctx, req.(*OutpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BridgeService_ServiceDesc is the grpc.ServiceDesc for BridgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BridgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dcrpulse.gaming.v1.BridgeService",
	HandlerType: (*BridgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _BridgeService_Hello_Handler,
		},
		{
			MethodName: "Respond",
			Handler:    _BridgeService_Respond_Handler,
		},
		{
			MethodName: "ReportState",
			Handler:    _BridgeService_ReportState_Handler,
		},
		{
			MethodName: "RequestSpend",
			Handler:    _BridgeService_RequestSpend_Handler,
		},
		{
			MethodName: "SpendStatus",
			Handler:    _BridgeService_SpendStatus_Handler,
		},
		{
			MethodName: "Broadcast",
			Handler:    _BridgeService_Broadcast_Handler,
		},
		{
			MethodName: "SendFrame",
			Handler:    _BridgeService_SendFrame_Handler,
		},
		{
			MethodName: "ChainTip",
			Handler:    _BridgeService_ChainTip_Handler,
		},
		{
			MethodName: "BlockHash",
			Handler:    _BridgeService_BlockHash_Handler,
		},
		{
			MethodName: "Outpoint",
			Handler:    _BridgeService_Outpoint_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _BridgeService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gaming_bridge.proto",
}
