// The game <-> dcrpulse gaming bridge contract.
//
// The game is the gRPC CLIENT and dials the bridge over mTLS on a dedicated
// port. Its identity is NEVER a field in any message: it is the client
// certificate, resolved by the bridge from the verified peer. A game therefore
// cannot assert which game it is - it presents a credential and the bridge
// decides. One Subscribe stream carries every bridge->game push; everything the
// game initiates is a unary call. The bridge never dials the game, so a game
// behind NAT needs no inbound port.
//
// The bridge forms an opinion only on the money verbs and on routing. Frame
// contents are opaque: what a frame means is between the players, who sign
// their own traffic and check each other's, and a bridge that inspected
// payloads would be adding a party nobody agreed to trust.
//
// This file is the contract. A game generates its own client from it; there is
// no shared Go package, because the module path here is not fetchable. Changing
// it is changing a published wire format - see contract_test.go.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: gaming_bridge.proto

package gamingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Capability int32

const (
	Capability_CAP_UNSPECIFIED   Capability = 0
	Capability_CAP_ACCEPT_INVITE Capability = 1
	Capability_CAP_RECLAIM       Capability = 2
	Capability_CAP_SET_PAYOUT    Capability = 3
	Capability_CAP_SET_NAMES     Capability = 4
)

// Enum value maps for Capability.
var (
	Capability_name = map[int32]string{
		0: "CAP_UNSPECIFIED",
		1: "CAP_ACCEPT_INVITE",
		2: "CAP_RECLAIM",
		3: "CAP_SET_PAYOUT",
		4: "CAP_SET_NAMES",
	}
	Capability_value = map[string]int32{
		"CAP_UNSPECIFIED":   0,
		"CAP_ACCEPT_INVITE": 1,
		"CAP_RECLAIM":       2,
		"CAP_SET_PAYOUT":    3,
		"CAP_SET_NAMES":     4,
	}
)

func (x Capability) Enum() *Capability {
	p := new(Capability)
	*p = x
	return p
}

func (x Capability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Capability) Descriptor() protoreflect.EnumDescriptor {
	return file_gaming_bridge_proto_enumTypes[0].Descriptor()
}

func (Capability) Type() protoreflect.EnumType {
	return &file_gaming_bridge_proto_enumTypes[0]
}

func (x Capability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Capability.Descriptor instead.
func (Capability) EnumDescriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{0}
}

type GapScope int32

const (
	GapScope_GAP_NONE   GapScope = 0
	GapScope_GAP_SCOPED GapScope = 1
	GapScope_GAP_ALL    GapScope = 2
)

// Enum value maps for GapScope.
var (
	GapScope_name = map[int32]string{
		0: "GAP_NONE",
		1: "GAP_SCOPED",
		2: "GAP_ALL",
	}
	GapScope_value = map[string]int32{
		"GAP_NONE":   0,
		"GAP_SCOPED": 1,
		"GAP_ALL":    2,
	}
)

func (x GapScope) Enum() *GapScope {
	p := new(GapScope)
	*p = x
	return p
}

func (x GapScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GapScope) Descriptor() protoreflect.EnumDescriptor {
	return file_gaming_bridge_proto_enumTypes[1].Descriptor()
}

func (GapScope) Type() protoreflect.EnumType {
	return &file_gaming_bridge_proto_enumTypes[1]
}

func (x GapScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GapScope.Descriptor instead.
func (GapScope) EnumDescriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{1}
}

type Reclaim_Kind int32

const (
	Reclaim_BOND       Reclaim_Kind = 0 // the standing fidelity bond
	Reclaim_STAKE      Reclaim_Kind = 1 // a table stake past its timelock
	Reclaim_TABLE_BOND Reclaim_Kind = 2 // a forfeitable table bond past its window
)

// Enum value maps for Reclaim_Kind.
var (
	Reclaim_Kind_name = map[int32]string{
		0: "BOND",
		1: "STAKE",
		2: "TABLE_BOND",
	}
	Reclaim_Kind_value = map[string]int32{
		"BOND":       0,
		"STAKE":      1,
		"TABLE_BOND": 2,
	}
)

func (x Reclaim_Kind) Enum() *Reclaim_Kind {
	p := new(Reclaim_Kind)
	*p = x
	return p
}

func (x Reclaim_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Reclaim_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_gaming_bridge_proto_enumTypes[2].Descriptor()
}

func (Reclaim_Kind) Type() protoreflect.EnumType {
	return &file_gaming_bridge_proto_enumTypes[2]
}

func (x Reclaim_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Reclaim_Kind.Descriptor instead.
func (Reclaim_Kind) EnumDescriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{9, 0}
}

type HelloRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// game_id is advisory. The bridge resolves identity from the credential and
	// refuses on mismatch, so a misdelivered credential is a visible
	// configuration error rather than a silent takeover.
	GameId string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	// game_protocol_version is the game's own wire version - the `gv=` key it
	// stamps on frames. Recorded and displayed, never enforced: a bridge that
	// refused an unfamiliar version would have to be taught every game.
	GameProtocolVersion uint32 `protobuf:"varint,2,opt,name=game_protocol_version,json=gameProtocolVersion,proto3" json:"game_protocol_version,omitempty"`
	ClientVersion       string `protobuf:"bytes,3,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	// capabilities are the pushes this game can answer. One that cannot do a
	// thing says so, and the console stops offering it - which is how this
	// contract grows without every game having to grow with it.
	Capabilities  []Capability `protobuf:"varint,4,rep,packed,name=capabilities,proto3,enum=dcrpulse.gaming.v1.Capability" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_gaming_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *HelloRequest) GetGameProtocolVersion() uint32 {
	if x != nil {
		return x.GameProtocolVersion
	}
	return 0
}

func (x *HelloRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *HelloRequest) GetCapabilities() []Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type HelloReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// game is authoritative: the id the bridge resolved from the credential. The
	// game learns what it is rather than asserting it.
	Game                  string `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	BridgeContractVersion uint32 `protobuf:"varint,2,opt,name=bridge_contract_version,json=bridgeContractVersion,proto3" json:"bridge_contract_version,omitempty"`
	// network is the chain this bridge is on. The game MUST refuse to proceed on
	// a mismatch: a game built for one network against a bridge on another makes
	// scripts nobody can spend and pays real money into them.
	Network string `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	// chain_available says whether the node is reachable yet, so a game knows
	// before its first ChainTip rather than discovering it as an error.
	ChainAvailable bool           `protobuf:"varint,4,opt,name=chain_available,json=chainAvailable,proto3" json:"chain_available,omitempty"`
	Policy         *PolicySummary `protobuf:"bytes,5,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_gaming_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *HelloReply) GetBridgeContractVersion() uint32 {
	if x != nil {
		return x.BridgeContractVersion
	}
	return 0
}

func (x *HelloReply) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *HelloReply) GetChainAvailable() bool {
	if x != nil {
		return x.ChainAvailable
	}
	return false
}

func (x *HelloReply) GetPolicy() *PolicySummary {
	if x != nil {
		return x.Policy
	}
	return nil
}

// PolicySummary lets a game say "that buy-in will be refused" before asking a
// person to try. It is a courtesy, not the enforcement - the caps are applied
// at RequestSpend whatever the game believes.
type PolicySummary struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PerTableCapAtoms int64                  `protobuf:"varint,1,opt,name=per_table_cap_atoms,json=perTableCapAtoms,proto3" json:"per_table_cap_atoms,omitempty"`
	PerDayCapAtoms   int64                  `protobuf:"varint,2,opt,name=per_day_cap_atoms,json=perDayCapAtoms,proto3" json:"per_day_cap_atoms,omitempty"`
	AccountBound     bool                   `protobuf:"varint,3,opt,name=account_bound,json=accountBound,proto3" json:"account_bound,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PolicySummary) Reset() {
	*x = PolicySummary{}
	mi := &file_gaming_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicySummary) ProtoMessage() {}

func (x *PolicySummary) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicySummary.ProtoReflect.Descriptor instead.
func (*PolicySummary) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *PolicySummary) GetPerTableCapAtoms() int64 {
	if x != nil {
		return x.PerTableCapAtoms
	}
	return 0
}

func (x *PolicySummary) GetPerDayCapAtoms() int64 {
	if x != nil {
		return x.PerDayCapAtoms
	}
	return 0
}

func (x *PolicySummary) GetAccountBound() bool {
	if x != nil {
		return x.AccountBound
	}
	return false
}

type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// last_seq and epoch are what the game already holds. Sent back so the
	// bridge can tell a resumable reconnect from one that missed something.
	LastSeq       uint64 `protobuf:"varint,1,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	Epoch         string `protobuf:"bytes,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_gaming_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeRequest) GetLastSeq() uint64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *SubscribeRequest) GetEpoch() string {
	if x != nil {
		return x.Epoch
	}
	return ""
}

type BridgeEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*BridgeEvent_Start
	//	*BridgeEvent_Frame
	//	*BridgeEvent_Request
	//	*BridgeEvent_Spend
	Event         isBridgeEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BridgeEvent) Reset() {
	*x = BridgeEvent{}
	mi := &file_gaming_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeEvent) ProtoMessage() {}

func (x *BridgeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeEvent.ProtoReflect.Descriptor instead.
func (*BridgeEvent) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{4}
}

func (x *BridgeEvent) GetEvent() isBridgeEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *BridgeEvent) GetStart() *StreamStart {
	if x != nil {
		if x, ok := x.Event.(*BridgeEvent_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *BridgeEvent) GetFrame() *Frame {
	if x != nil {
		if x, ok := x.Event.(*BridgeEvent_Frame); ok {
			return x.Frame
		}
	}
	return nil
}

func (x *BridgeEvent) GetRequest() *BridgeRequest {
	if x != nil {
		if x, ok := x.Event.(*BridgeEvent_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *BridgeEvent) GetSpend() *SpendSettled {
	if x != nil {
		if x, ok := x.Event.(*BridgeEvent_Spend); ok {
			return x.Spend
		}
	}
	return nil
}

type isBridgeEvent_Event interface {
	isBridgeEvent_Event()
}

type BridgeEvent_Start struct {
	Start *StreamStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type BridgeEvent_Frame struct {
	Frame *Frame `protobuf:"bytes,2,opt,name=frame,proto3,oneof"`
}

type BridgeEvent_Request struct {
	Request *BridgeRequest `protobuf:"bytes,3,opt,name=request,proto3,oneof"`
}

type BridgeEvent_Spend struct {
	// spend is a hint that a request settled, to wake a poll early. It is
	// never the answer: the game must call SpendStatus and write that.
	Spend *SpendSettled `protobuf:"bytes,4,opt,name=spend,proto3,oneof"`
}

func (*BridgeEvent_Start) isBridgeEvent_Event() {}

func (*BridgeEvent_Frame) isBridgeEvent_Event() {}

func (*BridgeEvent_Request) isBridgeEvent_Event() {}

func (*BridgeEvent_Spend) isBridgeEvent_Event() {}

// StreamStart is the first event on every stream, and the only place a gap is
// declared.
//
// A game must resync when and only when gap is true. Inferring a gap from its
// own reconnect loop is what makes a brief outage cost one resync per attempt
// per table; stating it once means a failed dial costs nothing at all.
type StreamStart struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Epoch    string                 `protobuf:"bytes,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	FromSeq  uint64                 `protobuf:"varint,2,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"`
	Gap      bool                   `protobuf:"varint,3,opt,name=gap,proto3" json:"gap,omitempty"`
	GapScope GapScope               `protobuf:"varint,4,opt,name=gap_scope,json=gapScope,proto3,enum=dcrpulse.gaming.v1.GapScope" json:"gap_scope,omitempty"`
	// gap_gcids names the tables actually missed, when the bridge knows. A
	// scoped gap resyncs one table instead of all of them.
	GapGcids      []string `protobuf:"bytes,5,rep,name=gap_gcids,json=gapGcids,proto3" json:"gap_gcids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStart) Reset() {
	*x = StreamStart{}
	mi := &file_gaming_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStart) ProtoMessage() {}

func (x *StreamStart) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStart.ProtoReflect.Descriptor instead.
func (*StreamStart) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{5}
}

func (x *StreamStart) GetEpoch() string {
	if x != nil {
		return x.Epoch
	}
	return ""
}

func (x *StreamStart) GetFromSeq() uint64 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

func (x *StreamStart) GetGap() bool {
	if x != nil {
		return x.Gap
	}
	return false
}

func (x *StreamStart) GetGapScope() GapScope {
	if x != nil {
		return x.GapScope
	}
	return GapScope_GAP_NONE
}

func (x *StreamStart) GetGapGcids() []string {
	if x != nil {
		return x.GapGcids
	}
	return nil
}

type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Seq   uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// gcid is the group chat, which for a game is the table.
	Gcid string `protobuf:"bytes,2,opt,name=gcid,proto3" json:"gcid,omitempty"`
	// from is the sender's authenticated Bison Relay uid. It comes from the
	// ratcheted message, never from anything inside the payload, so no payload
	// field can forge it.
	From string `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	// frame is the whole envelope, exactly as it arrived.
	Frame         string `protobuf:"bytes,4,opt,name=frame,proto3" json:"frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_gaming_bridge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{6}
}

func (x *Frame) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Frame) GetGcid() string {
	if x != nil {
		return x.Gcid
	}
	return ""
}

func (x *Frame) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Frame) GetFrame() string {
	if x != nil {
		return x.Frame
	}
	return ""
}

// BridgeRequest is work the operator asked for, addressed to this game. Every
// one is answered by Respond: these are calls whose replies the console shows,
// not announcements.
type BridgeRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// deadline_unix is advisory for reads. A Reclaim MUST be completed and
	// broadcast regardless - the coin is coming home either way - and its
	// outcome reported through ReportState, which is the backstop for a reply
	// that never arrived.
	DeadlineUnix int64 `protobuf:"varint,2,opt,name=deadline_unix,json=deadlineUnix,proto3" json:"deadline_unix,omitempty"`
	// Types that are valid to be assigned to Req:
	//
	//	*BridgeRequest_AcceptInvite
	//	*BridgeRequest_Reclaim
	//	*BridgeRequest_SetPayout
	//	*BridgeRequest_SetNames
	//	*BridgeRequest_RefreshState
	Req           isBridgeRequest_Req `protobuf_oneof:"req"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BridgeRequest) Reset() {
	*x = BridgeRequest{}
	mi := &file_gaming_bridge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeRequest) ProtoMessage() {}

func (x *BridgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeRequest.ProtoReflect.Descriptor instead.
func (*BridgeRequest) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{7}
}

func (x *BridgeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BridgeRequest) GetDeadlineUnix() int64 {
	if x != nil {
		return x.DeadlineUnix
	}
	return 0
}

func (x *BridgeRequest) GetReq() isBridgeRequest_Req {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *BridgeRequest) GetAcceptInvite() *AcceptInvite {
	if x != nil {
		if x, ok := x.Req.(*BridgeRequest_AcceptInvite); ok {
			return x.AcceptInvite
		}
	}
	return nil
}

func (x *BridgeRequest) GetReclaim() *Reclaim {
	if x != nil {
		if x, ok := x.Req.(*BridgeRequest_Reclaim); ok {
			return x.Reclaim
		}
	}
	return nil
}

func (x *BridgeRequest) GetSetPayout() *SetPayoutAddress {
	if x != nil {
		if x, ok := x.Req.(*BridgeRequest_SetPayout); ok {
			return x.SetPayout
		}
	}
	return nil
}

func (x *BridgeRequest) GetSetNames() *SetNames {
	if x != nil {
		if x, ok := x.Req.(*BridgeRequest_SetNames); ok {
			return x.SetNames
		}
	}
	return nil
}

func (x *BridgeRequest) GetRefreshState() *RefreshState {
	if x != nil {
		if x, ok := x.Req.(*BridgeRequest_RefreshState); ok {
			return x.RefreshState
		}
	}
	return nil
}

type isBridgeRequest_Req interface {
	isBridgeRequest_Req()
}

type BridgeRequest_AcceptInvite struct {
	AcceptInvite *AcceptInvite `protobuf:"bytes,3,opt,name=accept_invite,json=acceptInvite,proto3,oneof"`
}

type BridgeRequest_Reclaim struct {
	Reclaim *Reclaim `protobuf:"bytes,4,opt,name=reclaim,proto3,oneof"`
}

type BridgeRequest_SetPayout struct {
	SetPayout *SetPayoutAddress `protobuf:"bytes,5,opt,name=set_payout,json=setPayout,proto3,oneof"`
}

type BridgeRequest_SetNames struct {
	SetNames *SetNames `protobuf:"bytes,6,opt,name=set_names,json=setNames,proto3,oneof"`
}

type BridgeRequest_RefreshState struct {
	RefreshState *RefreshState `protobuf:"bytes,7,opt,name=refresh_state,json=refreshState,proto3,oneof"`
}

func (*BridgeRequest_AcceptInvite) isBridgeRequest_Req() {}

func (*BridgeRequest_Reclaim) isBridgeRequest_Req() {}

func (*BridgeRequest_SetPayout) isBridgeRequest_Req() {}

func (*BridgeRequest_SetNames) isBridgeRequest_Req() {}

func (*BridgeRequest_RefreshState) isBridgeRequest_Req() {}

type AcceptInvite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invite        string                 `protobuf:"bytes,1,opt,name=invite,proto3" json:"invite,omitempty"`
	Gcid          string                 `protobuf:"bytes,2,opt,name=gcid,proto3" json:"gcid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptInvite) Reset() {
	*x = AcceptInvite{}
	mi := &file_gaming_bridge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInvite) ProtoMessage() {}

func (x *AcceptInvite) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInvite.ProtoReflect.Descriptor instead.
func (*AcceptInvite) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{8}
}

func (x *AcceptInvite) GetInvite() string {
	if x != nil {
		return x.Invite
	}
	return ""
}

func (x *AcceptInvite) GetGcid() string {
	if x != nil {
		return x.Gcid
	}
	return ""
}

type Reclaim struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  Reclaim_Kind           `protobuf:"varint,1,opt,name=kind,proto3,enum=dcrpulse.gaming.v1.Reclaim_Kind" json:"kind,omitempty"`
	Sid   string                 `protobuf:"bytes,2,opt,name=sid,proto3" json:"sid,omitempty"`
	// dest_addr is derived by the bridge from the game's own bound account. A
	// game that chose where its refunds landed could simply choose itself.
	DestAddr string `protobuf:"bytes,3,opt,name=dest_addr,json=destAddr,proto3" json:"dest_addr,omitempty"`
	// outpoint names coin other than the seat's current stake - the way back for
	// a deposit that was paid but never recorded.
	Outpoint string `protobuf:"bytes,4,opt,name=outpoint,proto3" json:"outpoint,omitempty"`
	// fee_atoms of 0 means the game's own default.
	FeeAtoms      int64 `protobuf:"varint,5,opt,name=fee_atoms,json=feeAtoms,proto3" json:"fee_atoms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reclaim) Reset() {
	*x = Reclaim{}
	mi := &file_gaming_bridge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reclaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reclaim) ProtoMessage() {}

func (x *Reclaim) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reclaim.ProtoReflect.Descriptor instead.
func (*Reclaim) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{9}
}

func (x *Reclaim) GetKind() Reclaim_Kind {
	if x != nil {
		return x.Kind
	}
	return Reclaim_BOND
}

func (x *Reclaim) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *Reclaim) GetDestAddr() string {
	if x != nil {
		return x.DestAddr
	}
	return ""
}

func (x *Reclaim) GetOutpoint() string {
	if x != nil {
		return x.Outpoint
	}
	return ""
}

func (x *Reclaim) GetFeeAtoms() int64 {
	if x != nil {
		return x.FeeAtoms
	}
	return 0
}

// SetPayoutAddress says where this player's winnings are to be paid.
//
// address is derived by the bridge from the game's own bound account, for the
// same reason a Reclaim's dest_addr is: a game that chose where its winnings
// landed could simply choose itself.
//
// Every seat must answer before a table can pay anybody: the settlement spends
// the table's escrow and needs every signature, so one seat that has not said
// holds up everyone's money.
type SetPayoutAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPayoutAddress) Reset() {
	*x = SetPayoutAddress{}
	mi := &file_gaming_bridge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPayoutAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPayoutAddress) ProtoMessage() {}

func (x *SetPayoutAddress) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPayoutAddress.ProtoReflect.Descriptor instead.
func (*SetPayoutAddress) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{10}
}

func (x *SetPayoutAddress) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// SetNames is merged, not replaced: labels are cosmetic and a partial update
// must not erase what it does not mention.
type SetNames struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         map[string]string      `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNames) Reset() {
	*x = SetNames{}
	mi := &file_gaming_bridge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNames) ProtoMessage() {}

func (x *SetNames) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNames.ProtoReflect.Descriptor instead.
func (*SetNames) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{11}
}

func (x *SetNames) GetNames() map[string]string {
	if x != nil {
		return x.Names
	}
	return nil
}

type RefreshState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshState) Reset() {
	*x = RefreshState{}
	mi := &file_gaming_bridge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshState) ProtoMessage() {}

func (x *RefreshState) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshState.ProtoReflect.Descriptor instead.
func (*RefreshState) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{12}
}

type RespondRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// ok false carries the game's own words, which is the useful part - a
	// refusal that says how many blocks are left on a lock is worth more than
	// one that says no.
	Ok    bool   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*RespondRequest_AcceptInvite
	//	*RespondRequest_Reclaim
	//	*RespondRequest_State
	Result        isRespondRequest_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondRequest) Reset() {
	*x = RespondRequest{}
	mi := &file_gaming_bridge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondRequest) ProtoMessage() {}

func (x *RespondRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondRequest.ProtoReflect.Descriptor instead.
func (*RespondRequest) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{13}
}

func (x *RespondRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RespondRequest) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RespondRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RespondRequest) GetResult() isRespondRequest_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RespondRequest) GetAcceptInvite() *AcceptInviteResult {
	if x != nil {
		if x, ok := x.Result.(*RespondRequest_AcceptInvite); ok {
			return x.AcceptInvite
		}
	}
	return nil
}

func (x *RespondRequest) GetReclaim() *ReclaimResult {
	if x != nil {
		if x, ok := x.Result.(*RespondRequest_Reclaim); ok {
			return x.Reclaim
		}
	}
	return nil
}

func (x *RespondRequest) GetState() *GameState {
	if x != nil {
		if x, ok := x.Result.(*RespondRequest_State); ok {
			return x.State
		}
	}
	return nil
}

type isRespondRequest_Result interface {
	isRespondRequest_Result()
}

type RespondRequest_AcceptInvite struct {
	AcceptInvite *AcceptInviteResult `protobuf:"bytes,4,opt,name=accept_invite,json=acceptInvite,proto3,oneof"`
}

type RespondRequest_Reclaim struct {
	Reclaim *ReclaimResult `protobuf:"bytes,5,opt,name=reclaim,proto3,oneof"`
}

type RespondRequest_State struct {
	State *GameState `protobuf:"bytes,6,opt,name=state,proto3,oneof"`
}

func (*RespondRequest_AcceptInvite) isRespondRequest_Result() {}

func (*RespondRequest_Reclaim) isRespondRequest_Result() {}

func (*RespondRequest_State) isRespondRequest_Result() {}

type RespondReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondReply) Reset() {
	*x = RespondReply{}
	mi := &file_gaming_bridge_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondReply) ProtoMessage() {}

func (x *RespondReply) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondReply.ProtoReflect.Descriptor instead.
func (*RespondReply) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{14}
}

type AcceptInviteResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           string                 `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptInviteResult) Reset() {
	*x = AcceptInviteResult{}
	mi := &file_gaming_bridge_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptInviteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInviteResult) ProtoMessage() {}

func (x *AcceptInviteResult) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInviteResult.ProtoReflect.Descriptor instead.
func (*AcceptInviteResult) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{15}
}

func (x *AcceptInviteResult) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

type ReclaimResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txid          string                 `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReclaimResult) Reset() {
	*x = ReclaimResult{}
	mi := &file_gaming_bridge_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReclaimResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReclaimResult) ProtoMessage() {}

func (x *ReclaimResult) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReclaimResult.ProtoReflect.Descriptor instead.
func (*ReclaimResult) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{16}
}

func (x *ReclaimResult) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

// GameState is everything the console shows about one game. Sent when
// something moves, and in answer to RefreshState.
type GameState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request_id is set only when this answers a RefreshState.
	RequestId  string       `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ReportedAt int64        `protobuf:"varint,2,opt,name=reported_at,json=reportedAt,proto3" json:"reported_at,omitempty"`
	Seq        uint64       `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Tables     []*Table     `protobuf:"bytes,4,rep,name=tables,proto3" json:"tables,omitempty"`
	Bond       *Bond        `protobuf:"bytes,5,opt,name=bond,proto3" json:"bond,omitempty"`
	TableBonds []*TableBond `protobuf:"bytes,6,rep,name=table_bonds,json=tableBonds,proto3" json:"table_bonds,omitempty"`
	// payout_address is echoed back so the console can see a push that did not
	// take.
	PayoutAddress string `protobuf:"bytes,7,opt,name=payout_address,json=payoutAddress,proto3" json:"payout_address,omitempty"`
	ChainErr      string `protobuf:"bytes,8,opt,name=chain_err,json=chainErr,proto3" json:"chain_err,omitempty"`
	// seed_backup_acknowledged stops the console nagging. The seed itself never
	// crosses this bridge: it is the one secret the operator does not otherwise
	// hold, and the game offers its own backup where the person already is.
	SeedBackupAcknowledged bool `protobuf:"varint,9,opt,name=seed_backup_acknowledged,json=seedBackupAcknowledged,proto3" json:"seed_backup_acknowledged,omitempty"`
	// stakes is every seat of ours still holding a buy-in.
	Stakes        []*Stake `protobuf:"bytes,10,rep,name=stakes,proto3" json:"stakes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_gaming_bridge_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{17}
}

func (x *GameState) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GameState) GetReportedAt() int64 {
	if x != nil {
		return x.ReportedAt
	}
	return 0
}

func (x *GameState) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GameState) GetTables() []*Table {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *GameState) GetBond() *Bond {
	if x != nil {
		return x.Bond
	}
	return nil
}

func (x *GameState) GetTableBonds() []*TableBond {
	if x != nil {
		return x.TableBonds
	}
	return nil
}

func (x *GameState) GetPayoutAddress() string {
	if x != nil {
		return x.PayoutAddress
	}
	return ""
}

func (x *GameState) GetChainErr() string {
	if x != nil {
		return x.ChainErr
	}
	return ""
}

func (x *GameState) GetSeedBackupAcknowledged() bool {
	if x != nil {
		return x.SeedBackupAcknowledged
	}
	return false
}

func (x *GameState) GetStakes() []*Stake {
	if x != nil {
		return x.Stakes
	}
	return nil
}

type ReportStateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportStateReply) Reset() {
	*x = ReportStateReply{}
	mi := &file_gaming_bridge_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStateReply) ProtoMessage() {}

func (x *ReportStateReply) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStateReply.ProtoReflect.Descriptor instead.
func (*ReportStateReply) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{18}
}

type Table struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Sid        string                 `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Gcid       string                 `protobuf:"bytes,2,opt,name=gcid,proto3" json:"gcid,omitempty"`
	State      string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Seats      uint32                 `protobuf:"varint,4,opt,name=seats,proto3" json:"seats,omitempty"`
	BuyinAtoms int64                  `protobuf:"varint,5,opt,name=buyin_atoms,json=buyinAtoms,proto3" json:"buyin_atoms,omitempty"`
	Until      uint32                 `protobuf:"varint,6,opt,name=until,proto3" json:"until,omitempty"`
	Over       bool                   `protobuf:"varint,7,opt,name=over,proto3" json:"over,omitempty"`
	// settling is true while this game could still complete a cooperative
	// settlement for the table. A refund taken during that window spends an
	// input the settlement needs, so the console does not offer one.
	Settling      bool `protobuf:"varint,8,opt,name=settling,proto3" json:"settling,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_gaming_bridge_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{19}
}

func (x *Table) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *Table) GetGcid() string {
	if x != nil {
		return x.Gcid
	}
	return ""
}

func (x *Table) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Table) GetSeats() uint32 {
	if x != nil {
		return x.Seats
	}
	return 0
}

func (x *Table) GetBuyinAtoms() int64 {
	if x != nil {
		return x.BuyinAtoms
	}
	return 0
}

func (x *Table) GetUntil() uint32 {
	if x != nil {
		return x.Until
	}
	return 0
}

func (x *Table) GetOver() bool {
	if x != nil {
		return x.Over
	}
	return false
}

func (x *Table) GetSettling() bool {
	if x != nil {
		return x.Settling
	}
	return false
}

// Bond and TableBond carry absolute facts only. A count of blocks remaining is
// true for one block and then quietly wrong; a maturity height stays true while
// the game is away, and the console derives the rest from the bridge's own tip.
type Bond struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Address    string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	ScriptHex  string                 `protobuf:"bytes,2,opt,name=script_hex,json=scriptHex,proto3" json:"script_hex,omitempty"`
	Outpoint   string                 `protobuf:"bytes,3,opt,name=outpoint,proto3" json:"outpoint,omitempty"`
	MinAtoms   int64                  `protobuf:"varint,4,opt,name=min_atoms,json=minAtoms,proto3" json:"min_atoms,omitempty"`
	Atoms      int64                  `protobuf:"varint,5,opt,name=atoms,proto3" json:"atoms,omitempty"`
	MaturesAt  int64                  `protobuf:"varint,6,opt,name=matures_at,json=maturesAt,proto3" json:"matures_at,omitempty"`
	HasDeposit bool                   `protobuf:"varint,7,opt,name=has_deposit,json=hasDeposit,proto3" json:"has_deposit,omitempty"`
	Spent      bool                   `protobuf:"varint,8,opt,name=spent,proto3" json:"spent,omitempty"`
	// spending is true while a spend of this output is in the mempool.
	Spending      bool `protobuf:"varint,9,opt,name=spending,proto3" json:"spending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bond) Reset() {
	*x = Bond{}
	mi := &file_gaming_bridge_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bond) ProtoMessage() {}

func (x *Bond) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bond.ProtoReflect.Descriptor instead.
func (*Bond) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{20}
}

func (x *Bond) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Bond) GetScriptHex() string {
	if x != nil {
		return x.ScriptHex
	}
	return ""
}

func (x *Bond) GetOutpoint() string {
	if x != nil {
		return x.Outpoint
	}
	return ""
}

func (x *Bond) GetMinAtoms() int64 {
	if x != nil {
		return x.MinAtoms
	}
	return 0
}

func (x *Bond) GetAtoms() int64 {
	if x != nil {
		return x.Atoms
	}
	return 0
}

func (x *Bond) GetMaturesAt() int64 {
	if x != nil {
		return x.MaturesAt
	}
	return 0
}

func (x *Bond) GetHasDeposit() bool {
	if x != nil {
		return x.HasDeposit
	}
	return false
}

func (x *Bond) GetSpent() bool {
	if x != nil {
		return x.Spent
	}
	return false
}

func (x *Bond) GetSpending() bool {
	if x != nil {
		return x.Spending
	}
	return false
}

type TableBond struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Sid       string                 `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Seat      uint32                 `protobuf:"varint,2,opt,name=seat,proto3" json:"seat,omitempty"`
	Outpoint  string                 `protobuf:"bytes,3,opt,name=outpoint,proto3" json:"outpoint,omitempty"`
	Address   string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Atoms     int64                  `protobuf:"varint,5,opt,name=atoms,proto3" json:"atoms,omitempty"`
	MaturesAt int64                  `protobuf:"varint,6,opt,name=matures_at,json=maturesAt,proto3" json:"matures_at,omitempty"`
	Spent     bool                   `protobuf:"varint,7,opt,name=spent,proto3" json:"spent,omitempty"`
	// spending is true while a spend of this output is in the mempool. Distinct
	// from spent, which is the chain's settled answer: a broadcast can still be
	// evicted, so the outpoint stays reported and stays this game's to reclaim.
	Spending      bool `protobuf:"varint,8,opt,name=spending,proto3" json:"spending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableBond) Reset() {
	*x = TableBond{}
	mi := &file_gaming_bridge_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableBond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableBond) ProtoMessage() {}

func (x *TableBond) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableBond.ProtoReflect.Descriptor instead.
func (*TableBond) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{21}
}

func (x *TableBond) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *TableBond) GetSeat() uint32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *TableBond) GetOutpoint() string {
	if x != nil {
		return x.Outpoint
	}
	return ""
}

func (x *TableBond) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TableBond) GetAtoms() int64 {
	if x != nil {
		return x.Atoms
	}
	return 0
}

func (x *TableBond) GetMaturesAt() int64 {
	if x != nil {
		return x.MaturesAt
	}
	return 0
}

func (x *TableBond) GetSpent() bool {
	if x != nil {
		return x.Spent
	}
	return false
}

func (x *TableBond) GetSpending() bool {
	if x != nil {
		return x.Spending
	}
	return false
}

// Stake is one seat's buy-in, sitting behind its own refund timelock.
//
// Reported for the same reason a bond is: the console is where a person takes
// coin back, and it cannot offer that for an outpoint it was never told about.
type Stake struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Sid       string                 `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Seat      uint32                 `protobuf:"varint,2,opt,name=seat,proto3" json:"seat,omitempty"`
	Outpoint  string                 `protobuf:"bytes,3,opt,name=outpoint,proto3" json:"outpoint,omitempty"`
	Address   string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Atoms     int64                  `protobuf:"varint,5,opt,name=atoms,proto3" json:"atoms,omitempty"`
	MaturesAt int64                  `protobuf:"varint,6,opt,name=matures_at,json=maturesAt,proto3" json:"matures_at,omitempty"`
	Spent     bool                   `protobuf:"varint,7,opt,name=spent,proto3" json:"spent,omitempty"`
	// spending is true while a spend of this output is in the mempool. Distinct
	// from spent, which is the chain's settled answer: a broadcast can still be
	// evicted, so the outpoint stays reported and stays this game's to reclaim.
	Spending      bool `protobuf:"varint,8,opt,name=spending,proto3" json:"spending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stake) Reset() {
	*x = Stake{}
	mi := &file_gaming_bridge_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stake) ProtoMessage() {}

func (x *Stake) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stake.ProtoReflect.Descriptor instead.
func (*Stake) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{22}
}

func (x *Stake) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *Stake) GetSeat() uint32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *Stake) GetOutpoint() string {
	if x != nil {
		return x.Outpoint
	}
	return ""
}

func (x *Stake) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Stake) GetAtoms() int64 {
	if x != nil {
		return x.Atoms
	}
	return 0
}

func (x *Stake) GetMaturesAt() int64 {
	if x != nil {
		return x.MaturesAt
	}
	return 0
}

func (x *Stake) GetSpent() bool {
	if x != nil {
		return x.Spent
	}
	return false
}

func (x *Stake) GetSpending() bool {
	if x != nil {
		return x.Spending
	}
	return false
}

type RequestSpendRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Address     string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	AmountAtoms int64                  `protobuf:"varint,2,opt,name=amount_atoms,json=amountAtoms,proto3" json:"amount_atoms,omitempty"`
	// reason is prose a person reads on an approval screen, so it says what the
	// money buys and what gets it back.
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestSpendRequest) Reset() {
	*x = RequestSpendRequest{}
	mi := &file_gaming_bridge_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestSpendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSpendRequest) ProtoMessage() {}

func (x *RequestSpendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSpendRequest.ProtoReflect.Descriptor instead.
func (*RequestSpendRequest) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{23}
}

func (x *RequestSpendRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RequestSpendRequest) GetAmountAtoms() int64 {
	if x != nil {
		return x.AmountAtoms
	}
	return 0
}

func (x *RequestSpendRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SpendStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpendStatusRequest) Reset() {
	*x = SpendStatusRequest{}
	mi := &file_gaming_bridge_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpendStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendStatusRequest) ProtoMessage() {}

func (x *SpendStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendStatusRequest.ProtoReflect.Descriptor instead.
func (*SpendStatusRequest) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{24}
}

func (x *SpendStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Spend struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Game        string                 `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	Address     string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	AmountAtoms int64                  `protobuf:"varint,4,opt,name=amount_atoms,json=amountAtoms,proto3" json:"amount_atoms,omitempty"`
	Reason      string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	// state is pending, approved, denied, expired or failed.
	State         string `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	Txid          string `protobuf:"bytes,7,opt,name=txid,proto3" json:"txid,omitempty"`
	Error         string `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	RequestedAt   int64  `protobuf:"varint,9,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	DecidedAt     int64  `protobuf:"varint,10,opt,name=decided_at,json=decidedAt,proto3" json:"decided_at,omitempty"`
	ExpiresAt     int64  `protobuf:"varint,11,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spend) Reset() {
	*x = Spend{}
	mi := &file_gaming_bridge_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spend) ProtoMessage() {}

func (x *Spend) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spend.ProtoReflect.Descriptor instead.
func (*Spend) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{25}
}

func (x *Spend) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Spend) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *Spend) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Spend) GetAmountAtoms() int64 {
	if x != nil {
		return x.AmountAtoms
	}
	return 0
}

func (x *Spend) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Spend) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Spend) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

func (x *Spend) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Spend) GetRequestedAt() int64 {
	if x != nil {
		return x.RequestedAt
	}
	return 0
}

func (x *Spend) GetDecidedAt() int64 {
	if x != nil {
		return x.DecidedAt
	}
	return 0
}

func (x *Spend) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type SpendSettled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpendSettled) Reset() {
	*x = SpendSettled{}
	mi := &file_gaming_bridge_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpendSettled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendSettled) ProtoMessage() {}

func (x *SpendSettled) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendSettled.ProtoReflect.Descriptor instead.
func (*SpendSettled) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{26}
}

func (x *SpendSettled) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BroadcastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawTxHex      string                 `protobuf:"bytes,1,opt,name=raw_tx_hex,json=rawTxHex,proto3" json:"raw_tx_hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastRequest) Reset() {
	*x = BroadcastRequest{}
	mi := &file_gaming_bridge_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRequest) ProtoMessage() {}

func (x *BroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRequest.ProtoReflect.Descriptor instead.
func (*BroadcastRequest) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{27}
}

func (x *BroadcastRequest) GetRawTxHex() string {
	if x != nil {
		return x.RawTxHex
	}
	return ""
}

type BroadcastReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txid          string                 `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastReply) Reset() {
	*x = BroadcastReply{}
	mi := &file_gaming_bridge_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastReply) ProtoMessage() {}

func (x *BroadcastReply) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastReply.ProtoReflect.Descriptor instead.
func (*BroadcastReply) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{28}
}

func (x *BroadcastReply) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

type SendFrameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gcid          string                 `protobuf:"bytes,1,opt,name=gcid,proto3" json:"gcid,omitempty"`
	Frame         string                 `protobuf:"bytes,2,opt,name=frame,proto3" json:"frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFrameRequest) Reset() {
	*x = SendFrameRequest{}
	mi := &file_gaming_bridge_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFrameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFrameRequest) ProtoMessage() {}

func (x *SendFrameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFrameRequest.ProtoReflect.Descriptor instead.
func (*SendFrameRequest) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{29}
}

func (x *SendFrameRequest) GetGcid() string {
	if x != nil {
		return x.Gcid
	}
	return ""
}

func (x *SendFrameRequest) GetFrame() string {
	if x != nil {
		return x.Frame
	}
	return ""
}

type SendFrameReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFrameReply) Reset() {
	*x = SendFrameReply{}
	mi := &file_gaming_bridge_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFrameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFrameReply) ProtoMessage() {}

func (x *SendFrameReply) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFrameReply.ProtoReflect.Descriptor instead.
func (*SendFrameReply) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{30}
}

type ChainTipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainTipRequest) Reset() {
	*x = ChainTipRequest{}
	mi := &file_gaming_bridge_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainTipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainTipRequest) ProtoMessage() {}

func (x *ChainTipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainTipRequest.ProtoReflect.Descriptor instead.
func (*ChainTipRequest) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{31}
}

type ChainTipReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        int64                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainTipReply) Reset() {
	*x = ChainTipReply{}
	mi := &file_gaming_bridge_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainTipReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainTipReply) ProtoMessage() {}

func (x *ChainTipReply) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainTipReply.ProtoReflect.Descriptor instead.
func (*ChainTipReply) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{32}
}

func (x *ChainTipReply) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ChainTipReply) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type BlockHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint32                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockHashRequest) Reset() {
	*x = BlockHashRequest{}
	mi := &file_gaming_bridge_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHashRequest) ProtoMessage() {}

func (x *BlockHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHashRequest.ProtoReflect.Descriptor instead.
func (*BlockHashRequest) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{33}
}

func (x *BlockHashRequest) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type BlockHashReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint32                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockHashReply) Reset() {
	*x = BlockHashReply{}
	mi := &file_gaming_bridge_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHashReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHashReply) ProtoMessage() {}

func (x *BlockHashReply) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHashReply.ProtoReflect.Descriptor instead.
func (*BlockHashReply) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{34}
}

func (x *BlockHashReply) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockHashReply) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type OutpointRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Txid  string                 `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Vout  uint32                 `protobuf:"varint,2,opt,name=vout,proto3" json:"vout,omitempty"`
	// include_mempool is for finding coin this game has just paid, which is in
	// no block yet. Judging somebody else's bond needs a buried output, and a
	// game that confuses the two is trusting an unconfirmed stranger.
	IncludeMempool bool `protobuf:"varint,3,opt,name=include_mempool,json=includeMempool,proto3" json:"include_mempool,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OutpointRequest) Reset() {
	*x = OutpointRequest{}
	mi := &file_gaming_bridge_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutpointRequest) ProtoMessage() {}

func (x *OutpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutpointRequest.ProtoReflect.Descriptor instead.
func (*OutpointRequest) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{35}
}

func (x *OutpointRequest) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

func (x *OutpointRequest) GetVout() uint32 {
	if x != nil {
		return x.Vout
	}
	return 0
}

func (x *OutpointRequest) GetIncludeMempool() bool {
	if x != nil {
		return x.IncludeMempool
	}
	return false
}

type OutpointReply struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Found      bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	ValueAtoms int64                  `protobuf:"varint,2,opt,name=value_atoms,json=valueAtoms,proto3" json:"value_atoms,omitempty"`
	// pk_script_hex is how a game finds its own output among a transaction's
	// vouts. Without it an approved payment is money nobody can locate.
	PkScriptHex   string `protobuf:"bytes,3,opt,name=pk_script_hex,json=pkScriptHex,proto3" json:"pk_script_hex,omitempty"`
	Confirmations int64  `protobuf:"varint,4,opt,name=confirmations,proto3" json:"confirmations,omitempty"`
	Coinbase      bool   `protobuf:"varint,5,opt,name=coinbase,proto3" json:"coinbase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutpointReply) Reset() {
	*x = OutpointReply{}
	mi := &file_gaming_bridge_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutpointReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutpointReply) ProtoMessage() {}

func (x *OutpointReply) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_bridge_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutpointReply.ProtoReflect.Descriptor instead.
func (*OutpointReply) Descriptor() ([]byte, []int) {
	return file_gaming_bridge_proto_rawDescGZIP(), []int{36}
}

func (x *OutpointReply) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *OutpointReply) GetValueAtoms() int64 {
	if x != nil {
		return x.ValueAtoms
	}
	return 0
}

func (x *OutpointReply) GetPkScriptHex() string {
	if x != nil {
		return x.PkScriptHex
	}
	return ""
}

func (x *OutpointReply) GetConfirmations() int64 {
	if x != nil {
		return x.Confirmations
	}
	return 0
}

func (x *OutpointReply) GetCoinbase() bool {
	if x != nil {
		return x.Coinbase
	}
	return false
}

var File_gaming_bridge_proto protoreflect.FileDescriptor

const file_gaming_bridge_proto_rawDesc = "" +
	"\n" +
	"\x13gaming_bridge.proto\x12\x12dcrpulse.gaming.v1\"\xc6\x01\n" +
	"\fHelloRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x122\n" +
	"\x15game_protocol_version\x18\x02 \x01(\rR\x13gameProtocolVersion\x12%\n" +
	"\x0eclient_version\x18\x03 \x01(\tR\rclientVersion\x12B\n" +
	"\fcapabilities\x18\x04 \x03(\x0e2\x1e.dcrpulse.gaming.v1.CapabilityR\fcapabilities\"\xd6\x01\n" +
	"\n" +
	"HelloReply\x12\x12\n" +
	"\x04game\x18\x01 \x01(\tR\x04game\x126\n" +
	"\x17bridge_contract_version\x18\x02 \x01(\rR\x15bridgeContractVersion\x12\x18\n" +
	"\anetwork\x18\x03 \x01(\tR\anetwork\x12'\n" +
	"\x0fchain_available\x18\x04 \x01(\bR\x0echainAvailable\x129\n" +
	"\x06policy\x18\x05 \x01(\v2!.dcrpulse.gaming.v1.PolicySummaryR\x06policy\"\x8e\x01\n" +
	"\rPolicySummary\x12-\n" +
	"\x13per_table_cap_atoms\x18\x01 \x01(\x03R\x10perTableCapAtoms\x12)\n" +
	"\x11per_day_cap_atoms\x18\x02 \x01(\x03R\x0eperDayCapAtoms\x12#\n" +
	"\raccount_bound\x18\x03 \x01(\bR\faccountBound\"C\n" +
	"\x10SubscribeRequest\x12\x19\n" +
	"\blast_seq\x18\x01 \x01(\x04R\alastSeq\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\tR\x05epoch\"\xfb\x01\n" +
	"\vBridgeEvent\x127\n" +
	"\x05start\x18\x01 \x01(\v2\x1f.dcrpulse.gaming.v1.StreamStartH\x00R\x05start\x121\n" +
	"\x05frame\x18\x02 \x01(\v2\x19.dcrpulse.gaming.v1.FrameH\x00R\x05frame\x12=\n" +
	"\arequest\x18\x03 \x01(\v2!.dcrpulse.gaming.v1.BridgeRequestH\x00R\arequest\x128\n" +
	"\x05spend\x18\x04 \x01(\v2 .dcrpulse.gaming.v1.SpendSettledH\x00R\x05spendB\a\n" +
	"\x05event\"\xa8\x01\n" +
	"\vStreamStart\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\tR\x05epoch\x12\x19\n" +
	"\bfrom_seq\x18\x02 \x01(\x04R\afromSeq\x12\x10\n" +
	"\x03gap\x18\x03 \x01(\bR\x03gap\x129\n" +
	"\tgap_scope\x18\x04 \x01(\x0e2\x1c.dcrpulse.gaming.v1.GapScopeR\bgapScope\x12\x1b\n" +
	"\tgap_gcids\x18\x05 \x03(\tR\bgapGcids\"W\n" +
	"\x05Frame\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x12\n" +
	"\x04gcid\x18\x02 \x01(\tR\x04gcid\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\x12\x14\n" +
	"\x05frame\x18\x04 \x01(\tR\x05frame\"\xa9\x03\n" +
	"\rBridgeRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12#\n" +
	"\rdeadline_unix\x18\x02 \x01(\x03R\fdeadlineUnix\x12G\n" +
	"\raccept_invite\x18\x03 \x01(\v2 .dcrpulse.gaming.v1.AcceptInviteH\x00R\facceptInvite\x127\n" +
	"\areclaim\x18\x04 \x01(\v2\x1b.dcrpulse.gaming.v1.ReclaimH\x00R\areclaim\x12E\n" +
	"\n" +
	"set_payout\x18\x05 \x01(\v2$.dcrpulse.gaming.v1.SetPayoutAddressH\x00R\tsetPayout\x12;\n" +
	"\tset_names\x18\x06 \x01(\v2\x1c.dcrpulse.gaming.v1.SetNamesH\x00R\bsetNames\x12G\n" +
	"\rrefresh_state\x18\a \x01(\v2 .dcrpulse.gaming.v1.RefreshStateH\x00R\frefreshStateB\x05\n" +
	"\x03req\":\n" +
	"\fAcceptInvite\x12\x16\n" +
	"\x06invite\x18\x01 \x01(\tR\x06invite\x12\x12\n" +
	"\x04gcid\x18\x02 \x01(\tR\x04gcid\"\xd4\x01\n" +
	"\aReclaim\x124\n" +
	"\x04kind\x18\x01 \x01(\x0e2 .dcrpulse.gaming.v1.Reclaim.KindR\x04kind\x12\x10\n" +
	"\x03sid\x18\x02 \x01(\tR\x03sid\x12\x1b\n" +
	"\tdest_addr\x18\x03 \x01(\tR\bdestAddr\x12\x1a\n" +
	"\boutpoint\x18\x04 \x01(\tR\boutpoint\x12\x1b\n" +
	"\tfee_atoms\x18\x05 \x01(\x03R\bfeeAtoms\"+\n" +
	"\x04Kind\x12\b\n" +
	"\x04BOND\x10\x00\x12\t\n" +
	"\x05STAKE\x10\x01\x12\x0e\n" +
	"\n" +
	"TABLE_BOND\x10\x02\",\n" +
	"\x10SetPayoutAddress\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x83\x01\n" +
	"\bSetNames\x12=\n" +
	"\x05names\x18\x01 \x03(\v2'.dcrpulse.gaming.v1.SetNames.NamesEntryR\x05names\x1a8\n" +
	"\n" +
	"NamesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x0e\n" +
	"\fRefreshState\"\xa4\x02\n" +
	"\x0eRespondRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12M\n" +
	"\raccept_invite\x18\x04 \x01(\v2&.dcrpulse.gaming.v1.AcceptInviteResultH\x00R\facceptInvite\x12=\n" +
	"\areclaim\x18\x05 \x01(\v2!.dcrpulse.gaming.v1.ReclaimResultH\x00R\areclaim\x125\n" +
	"\x05state\x18\x06 \x01(\v2\x1d.dcrpulse.gaming.v1.GameStateH\x00R\x05stateB\b\n" +
	"\x06result\"\x0e\n" +
	"\fRespondReply\"&\n" +
	"\x12AcceptInviteResult\x12\x10\n" +
	"\x03sid\x18\x01 \x01(\tR\x03sid\"#\n" +
	"\rReclaimResult\x12\x12\n" +
	"\x04txid\x18\x01 \x01(\tR\x04txid\"\xaf\x03\n" +
	"\tGameState\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vreported_at\x18\x02 \x01(\x03R\n" +
	"reportedAt\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x121\n" +
	"\x06tables\x18\x04 \x03(\v2\x19.dcrpulse.gaming.v1.TableR\x06tables\x12,\n" +
	"\x04bond\x18\x05 \x01(\v2\x18.dcrpulse.gaming.v1.BondR\x04bond\x12>\n" +
	"\vtable_bonds\x18\x06 \x03(\v2\x1d.dcrpulse.gaming.v1.TableBondR\n" +
	"tableBonds\x12%\n" +
	"\x0epayout_address\x18\a \x01(\tR\rpayoutAddress\x12\x1b\n" +
	"\tchain_err\x18\b \x01(\tR\bchainErr\x128\n" +
	"\x18seed_backup_acknowledged\x18\t \x01(\bR\x16seedBackupAcknowledged\x121\n" +
	"\x06stakes\x18\n" +
	" \x03(\v2\x19.dcrpulse.gaming.v1.StakeR\x06stakes\"\x12\n" +
	"\x10ReportStateReply\"\xc0\x01\n" +
	"\x05Table\x12\x10\n" +
	"\x03sid\x18\x01 \x01(\tR\x03sid\x12\x12\n" +
	"\x04gcid\x18\x02 \x01(\tR\x04gcid\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x14\n" +
	"\x05seats\x18\x04 \x01(\rR\x05seats\x12\x1f\n" +
	"\vbuyin_atoms\x18\x05 \x01(\x03R\n" +
	"buyinAtoms\x12\x14\n" +
	"\x05until\x18\x06 \x01(\rR\x05until\x12\x12\n" +
	"\x04over\x18\a \x01(\bR\x04over\x12\x1a\n" +
	"\bsettling\x18\b \x01(\bR\bsettling\"\x80\x02\n" +
	"\x04Bond\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"script_hex\x18\x02 \x01(\tR\tscriptHex\x12\x1a\n" +
	"\boutpoint\x18\x03 \x01(\tR\boutpoint\x12\x1b\n" +
	"\tmin_atoms\x18\x04 \x01(\x03R\bminAtoms\x12\x14\n" +
	"\x05atoms\x18\x05 \x01(\x03R\x05atoms\x12\x1d\n" +
	"\n" +
	"matures_at\x18\x06 \x01(\x03R\tmaturesAt\x12\x1f\n" +
	"\vhas_deposit\x18\a \x01(\bR\n" +
	"hasDeposit\x12\x14\n" +
	"\x05spent\x18\b \x01(\bR\x05spent\x12\x1a\n" +
	"\bspending\x18\t \x01(\bR\bspending\"\xce\x01\n" +
	"\tTableBond\x12\x10\n" +
	"\x03sid\x18\x01 \x01(\tR\x03sid\x12\x12\n" +
	"\x04seat\x18\x02 \x01(\rR\x04seat\x12\x1a\n" +
	"\boutpoint\x18\x03 \x01(\tR\boutpoint\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x14\n" +
	"\x05atoms\x18\x05 \x01(\x03R\x05atoms\x12\x1d\n" +
	"\n" +
	"matures_at\x18\x06 \x01(\x03R\tmaturesAt\x12\x14\n" +
	"\x05spent\x18\a \x01(\bR\x05spent\x12\x1a\n" +
	"\bspending\x18\b \x01(\bR\bspending\"\xca\x01\n" +
	"\x05Stake\x12\x10\n" +
	"\x03sid\x18\x01 \x01(\tR\x03sid\x12\x12\n" +
	"\x04seat\x18\x02 \x01(\rR\x04seat\x12\x1a\n" +
	"\boutpoint\x18\x03 \x01(\tR\boutpoint\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x14\n" +
	"\x05atoms\x18\x05 \x01(\x03R\x05atoms\x12\x1d\n" +
	"\n" +
	"matures_at\x18\x06 \x01(\x03R\tmaturesAt\x12\x14\n" +
	"\x05spent\x18\a \x01(\bR\x05spent\x12\x1a\n" +
	"\bspending\x18\b \x01(\bR\bspending\"j\n" +
	"\x13RequestSpendRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12!\n" +
	"\famount_atoms\x18\x02 \x01(\x03R\vamountAtoms\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"$\n" +
	"\x12SpendStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa1\x02\n" +
	"\x05Spend\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04game\x18\x02 \x01(\tR\x04game\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12!\n" +
	"\famount_atoms\x18\x04 \x01(\x03R\vamountAtoms\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x12\x12\n" +
	"\x04txid\x18\a \x01(\tR\x04txid\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12!\n" +
	"\frequested_at\x18\t \x01(\x03R\vrequestedAt\x12\x1d\n" +
	"\n" +
	"decided_at\x18\n" +
	" \x01(\x03R\tdecidedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\v \x01(\x03R\texpiresAt\"\x1e\n" +
	"\fSpendSettled\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x10BroadcastRequest\x12\x1c\n" +
	"\n" +
	"raw_tx_hex\x18\x01 \x01(\tR\brawTxHex\"$\n" +
	"\x0eBroadcastReply\x12\x12\n" +
	"\x04txid\x18\x01 \x01(\tR\x04txid\"<\n" +
	"\x10SendFrameRequest\x12\x12\n" +
	"\x04gcid\x18\x01 \x01(\tR\x04gcid\x12\x14\n" +
	"\x05frame\x18\x02 \x01(\tR\x05frame\"\x10\n" +
	"\x0eSendFrameReply\"\x11\n" +
	"\x0fChainTipRequest\";\n" +
	"\rChainTipReply\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x03R\x06height\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\"*\n" +
	"\x10BlockHashRequest\x12\x16\n" +
	"\x06height\x18\x01 \x01(\rR\x06height\"<\n" +
	"\x0eBlockHashReply\x12\x16\n" +
	"\x06height\x18\x01 \x01(\rR\x06height\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\"b\n" +
	"\x0fOutpointRequest\x12\x12\n" +
	"\x04txid\x18\x01 \x01(\tR\x04txid\x12\x12\n" +
	"\x04vout\x18\x02 \x01(\rR\x04vout\x12'\n" +
	"\x0finclude_mempool\x18\x03 \x01(\bR\x0eincludeMempool\"\xac\x01\n" +
	"\rOutpointReply\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1f\n" +
	"\vvalue_atoms\x18\x02 \x01(\x03R\n" +
	"valueAtoms\x12\"\n" +
	"\rpk_script_hex\x18\x03 \x01(\tR\vpkScriptHex\x12$\n" +
	"\rconfirmations\x18\x04 \x01(\x03R\rconfirmations\x12\x1a\n" +
	"\bcoinbase\x18\x05 \x01(\bR\bcoinbase*p\n" +
	"\n" +
	"Capability\x12\x13\n" +
	"\x0fCAP_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CAP_ACCEPT_INVITE\x10\x01\x12\x0f\n" +
	"\vCAP_RECLAIM\x10\x02\x12\x12\n" +
	"\x0eCAP_SET_PAYOUT\x10\x03\x12\x11\n" +
	"\rCAP_SET_NAMES\x10\x04*5\n" +
	"\bGapScope\x12\f\n" +
	"\bGAP_NONE\x10\x00\x12\x0e\n" +
	"\n" +
	"GAP_SCOPED\x10\x01\x12\v\n" +
	"\aGAP_ALL\x10\x022\xa8\a\n" +
	"\rBridgeService\x12I\n" +
	"\x05Hello\x12 .dcrpulse.gaming.v1.HelloRequest\x1a\x1e.dcrpulse.gaming.v1.HelloReply\x12T\n" +
	"\tSubscribe\x12$.dcrpulse.gaming.v1.SubscribeRequest\x1a\x1f.dcrpulse.gaming.v1.BridgeEvent0\x01\x12O\n" +
	"\aRespond\x12\".dcrpulse.gaming.v1.RespondRequest\x1a .dcrpulse.gaming.v1.RespondReply\x12R\n" +
	"\vReportState\x12\x1d.dcrpulse.gaming.v1.GameState\x1a$.dcrpulse.gaming.v1.ReportStateReply\x12R\n" +
	"\fRequestSpend\x12'.dcrpulse.gaming.v1.RequestSpendRequest\x1a\x19.dcrpulse.gaming.v1.Spend\x12P\n" +
	"\vSpendStatus\x12&.dcrpulse.gaming.v1.SpendStatusRequest\x1a\x19.dcrpulse.gaming.v1.Spend\x12U\n" +
	"\tBroadcast\x12$.dcrpulse.gaming.v1.BroadcastRequest\x1a\".dcrpulse.gaming.v1.BroadcastReply\x12U\n" +
	"\tSendFrame\x12$.dcrpulse.gaming.v1.SendFrameRequest\x1a\".dcrpulse.gaming.v1.SendFrameReply\x12R\n" +
	"\bChainTip\x12#.dcrpulse.gaming.v1.ChainTipRequest\x1a!.dcrpulse.gaming.v1.ChainTipReply\x12U\n" +
	"\tBlockHash\x12$.dcrpulse.gaming.v1.BlockHashRequest\x1a\".dcrpulse.gaming.v1.BlockHashReply\x12R\n" +
	"\bOutpoint\x12#.dcrpulse.gaming.v1.OutpointRequest\x1a!.dcrpulse.gaming.v1.OutpointReplyB%Z#dcrpulse/internal/gamingpb;gamingpbb\x06proto3"

var (
	file_gaming_bridge_proto_rawDescOnce sync.Once
	file_gaming_bridge_proto_rawDescData []byte
)

func file_gaming_bridge_proto_rawDescGZIP() []byte {
	file_gaming_bridge_proto_rawDescOnce.Do(func() {
		file_gaming_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gaming_bridge_proto_rawDesc), len(file_gaming_bridge_proto_rawDesc)))
	})
	return file_gaming_bridge_proto_rawDescData
}

var file_gaming_bridge_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_gaming_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_gaming_bridge_proto_goTypes = []any{
	(Capability)(0),             // 0: dcrpulse.gaming.v1.Capability
	(GapScope)(0),               // 1: dcrpulse.gaming.v1.GapScope
	(Reclaim_Kind)(0),           // 2: dcrpulse.gaming.v1.Reclaim.Kind
	(*HelloRequest)(nil),        // 3: dcrpulse.gaming.v1.HelloRequest
	(*HelloReply)(nil),          // 4: dcrpulse.gaming.v1.HelloReply
	(*PolicySummary)(nil),       // 5: dcrpulse.gaming.v1.PolicySummary
	(*SubscribeRequest)(nil),    // 6: dcrpulse.gaming.v1.SubscribeRequest
	(*BridgeEvent)(nil),         // 7: dcrpulse.gaming.v1.BridgeEvent
	(*StreamStart)(nil),         // 8: dcrpulse.gaming.v1.StreamStart
	(*Frame)(nil),               // 9: dcrpulse.gaming.v1.Frame
	(*BridgeRequest)(nil),       // 10: dcrpulse.gaming.v1.BridgeRequest
	(*AcceptInvite)(nil),        // 11: dcrpulse.gaming.v1.AcceptInvite
	(*Reclaim)(nil),             // 12: dcrpulse.gaming.v1.Reclaim
	(*SetPayoutAddress)(nil),    // 13: dcrpulse.gaming.v1.SetPayoutAddress
	(*SetNames)(nil),            // 14: dcrpulse.gaming.v1.SetNames
	(*RefreshState)(nil),        // 15: dcrpulse.gaming.v1.RefreshState
	(*RespondRequest)(nil),      // 16: dcrpulse.gaming.v1.RespondRequest
	(*RespondReply)(nil),        // 17: dcrpulse.gaming.v1.RespondReply
	(*AcceptInviteResult)(nil),  // 18: dcrpulse.gaming.v1.AcceptInviteResult
	(*ReclaimResult)(nil),       // 19: dcrpulse.gaming.v1.ReclaimResult
	(*GameState)(nil),           // 20: dcrpulse.gaming.v1.GameState
	(*ReportStateReply)(nil),    // 21: dcrpulse.gaming.v1.ReportStateReply
	(*Table)(nil),               // 22: dcrpulse.gaming.v1.Table
	(*Bond)(nil),                // 23: dcrpulse.gaming.v1.Bond
	(*TableBond)(nil),           // 24: dcrpulse.gaming.v1.TableBond
	(*Stake)(nil),               // 25: dcrpulse.gaming.v1.Stake
	(*RequestSpendRequest)(nil), // 26: dcrpulse.gaming.v1.RequestSpendRequest
	(*SpendStatusRequest)(nil),  // 27: dcrpulse.gaming.v1.SpendStatusRequest
	(*Spend)(nil),               // 28: dcrpulse.gaming.v1.Spend
	(*SpendSettled)(nil),        // 29: dcrpulse.gaming.v1.SpendSettled
	(*BroadcastRequest)(nil),    // 30: dcrpulse.gaming.v1.BroadcastRequest
	(*BroadcastReply)(nil),      // 31: dcrpulse.gaming.v1.BroadcastReply
	(*SendFrameRequest)(nil),    // 32: dcrpulse.gaming.v1.SendFrameRequest
	(*SendFrameReply)(nil),      // 33: dcrpulse.gaming.v1.SendFrameReply
	(*ChainTipRequest)(nil),     // 34: dcrpulse.gaming.v1.ChainTipRequest
	(*ChainTipReply)(nil),       // 35: dcrpulse.gaming.v1.ChainTipReply
	(*BlockHashRequest)(nil),    // 36: dcrpulse.gaming.v1.BlockHashRequest
	(*BlockHashReply)(nil),      // 37: dcrpulse.gaming.v1.BlockHashReply
	(*OutpointRequest)(nil),     // 38: dcrpulse.gaming.v1.OutpointRequest
	(*OutpointReply)(nil),       // 39: dcrpulse.gaming.v1.OutpointReply
	nil,                         // 40: dcrpulse.gaming.v1.SetNames.NamesEntry
}
var file_gaming_bridge_proto_depIdxs = []int32{
	0,  // 0: dcrpulse.gaming.v1.HelloRequest.capabilities:type_name -> dcrpulse.gaming.v1.Capability
	5,  // 1: dcrpulse.gaming.v1.HelloReply.policy:type_name -> dcrpulse.gaming.v1.PolicySummary
	8,  // 2: dcrpulse.gaming.v1.BridgeEvent.start:type_name -> dcrpulse.gaming.v1.StreamStart
	9,  // 3: dcrpulse.gaming.v1.BridgeEvent.frame:type_name -> dcrpulse.gaming.v1.Frame
	10, // 4: dcrpulse.gaming.v1.BridgeEvent.request:type_name -> dcrpulse.gaming.v1.BridgeRequest
	29, // 5: dcrpulse.gaming.v1.BridgeEvent.spend:type_name -> dcrpulse.gaming.v1.SpendSettled
	1,  // 6: dcrpulse.gaming.v1.StreamStart.gap_scope:type_name -> dcrpulse.gaming.v1.GapScope
	11, // 7: dcrpulse.gaming.v1.BridgeRequest.accept_invite:type_name -> dcrpulse.gaming.v1.AcceptInvite
	12, // 8: dcrpulse.gaming.v1.BridgeRequest.reclaim:type_name -> dcrpulse.gaming.v1.Reclaim
	13, // 9: dcrpulse.gaming.v1.BridgeRequest.set_payout:type_name -> dcrpulse.gaming.v1.SetPayoutAddress
	14, // 10: dcrpulse.gaming.v1.BridgeRequest.set_names:type_name -> dcrpulse.gaming.v1.SetNames
	15, // 11: dcrpulse.gaming.v1.BridgeRequest.refresh_state:type_name -> dcrpulse.gaming.v1.RefreshState
	2,  // 12: dcrpulse.gaming.v1.Reclaim.kind:type_name -> dcrpulse.gaming.v1.Reclaim.Kind
	40, // 13: dcrpulse.gaming.v1.SetNames.names:type_name -> dcrpulse.gaming.v1.SetNames.NamesEntry
	18, // 14: dcrpulse.gaming.v1.RespondRequest.accept_invite:type_name -> dcrpulse.gaming.v1.AcceptInviteResult
	19, // 15: dcrpulse.gaming.v1.RespondRequest.reclaim:type_name -> dcrpulse.gaming.v1.ReclaimResult
	20, // 16: dcrpulse.gaming.v1.RespondRequest.state:type_name -> dcrpulse.gaming.v1.GameState
	22, // 17: dcrpulse.gaming.v1.GameState.tables:type_name -> dcrpulse.gaming.v1.Table
	23, // 18: dcrpulse.gaming.v1.GameState.bond:type_name -> dcrpulse.gaming.v1.Bond
	24, // 19: dcrpulse.gaming.v1.GameState.table_bonds:type_name -> dcrpulse.gaming.v1.TableBond
	25, // 20: dcrpulse.gaming.v1.GameState.stakes:type_name -> dcrpulse.gaming.v1.Stake
	3,  // 21: dcrpulse.gaming.v1.BridgeService.Hello:input_type -> dcrpulse.gaming.v1.HelloRequest
	6,  // 22: dcrpulse.gaming.v1.BridgeService.Subscribe:input_type -> dcrpulse.gaming.v1.SubscribeRequest
	16, // 23: dcrpulse.gaming.v1.BridgeService.Respond:input_type -> dcrpulse.gaming.v1.RespondRequest
	20, // 24: dcrpulse.gaming.v1.BridgeService.ReportState:input_type -> dcrpulse.gaming.v1.GameState
	26, // 25: dcrpulse.gaming.v1.BridgeService.RequestSpend:input_type -> dcrpulse.gaming.v1.RequestSpendRequest
	27, // 26: dcrpulse.gaming.v1.BridgeService.SpendStatus:input_type -> dcrpulse.gaming.v1.SpendStatusRequest
	30, // 27: dcrpulse.gaming.v1.BridgeService.Broadcast:input_type -> dcrpulse.gaming.v1.BroadcastRequest
	32, // 28: dcrpulse.gaming.v1.BridgeService.SendFrame:input_type -> dcrpulse.gaming.v1.SendFrameRequest
	34, // 29: dcrpulse.gaming.v1.BridgeService.ChainTip:input_type -> dcrpulse.gaming.v1.ChainTipRequest
	36, // 30: dcrpulse.gaming.v1.BridgeService.BlockHash:input_type -> dcrpulse.gaming.v1.BlockHashRequest
	38, // 31: dcrpulse.gaming.v1.BridgeService.Outpoint:input_type -> dcrpulse.gaming.v1.OutpointRequest
	4,  // 32: dcrpulse.gaming.v1.BridgeService.Hello:output_type -> dcrpulse.gaming.v1.HelloReply
	7,  // 33: dcrpulse.gaming.v1.BridgeService.Subscribe:output_type -> dcrpulse.gaming.v1.BridgeEvent
	17, // 34: dcrpulse.gaming.v1.BridgeService.Respond:output_type -> dcrpulse.gaming.v1.RespondReply
	21, // 35: dcrpulse.gaming.v1.BridgeService.ReportState:output_type -> dcrpulse.gaming.v1.ReportStateReply
	28, // 36: dcrpulse.gaming.v1.BridgeService.RequestSpend:output_type -> dcrpulse.gaming.v1.Spend
	28, // 37: dcrpulse.gaming.v1.BridgeService.SpendStatus:output_type -> dcrpulse.gaming.v1.Spend
	31, // 38: dcrpulse.gaming.v1.BridgeService.Broadcast:output_type -> dcrpulse.gaming.v1.BroadcastReply
	33, // 39: dcrpulse.gaming.v1.BridgeService.SendFrame:output_type -> dcrpulse.gaming.v1.SendFrameReply
	35, // 40: dcrpulse.gaming.v1.BridgeService.ChainTip:output_type -> dcrpulse.gaming.v1.ChainTipReply
	37, // 41: dcrpulse.gaming.v1.BridgeService.BlockHash:output_type -> dcrpulse.gaming.v1.BlockHashReply
	39, // 42: dcrpulse.gaming.v1.BridgeService.Outpoint:output_type -> dcrpulse.gaming.v1.OutpointReply
	32, // [32:43] is the sub-list for method output_type
	21, // [21:32] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_gaming_bridge_proto_init() }
func file_gaming_bridge_proto_init() {
	if File_gaming_bridge_proto != nil {
		return
	}
	file_gaming_bridge_proto_msgTypes[4].OneofWrappers = []any{
		(*BridgeEvent_Start)(nil),
		(*BridgeEvent_Frame)(nil),
		(*BridgeEvent_Request)(nil),
		(*BridgeEvent_Spend)(nil),
	}
	file_gaming_bridge_proto_msgTypes[7].OneofWrappers = []any{
		(*BridgeRequest_AcceptInvite)(nil),
		(*BridgeRequest_Reclaim)(nil),
		(*BridgeRequest_SetPayout)(nil),
		(*BridgeRequest_SetNames)(nil),
		(*BridgeRequest_RefreshState)(nil),
	}
	file_gaming_bridge_proto_msgTypes[13].OneofWrappers = []any{
		(*RespondRequest_AcceptInvite)(nil),
		(*RespondRequest_Reclaim)(nil),
		(*RespondRequest_State)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gaming_bridge_proto_rawDesc), len(file_gaming_bridge_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gaming_bridge_proto_goTypes,
		DependencyIndexes: file_gaming_bridge_proto_depIdxs,
		EnumInfos:         file_gaming_bridge_proto_enumTypes,
		MessageInfos:      file_gaming_bridge_proto_msgTypes,
	}.Build()
	File_gaming_bridge_proto = out.File
	file_gaming_bridge_proto_goTypes = nil
	file_gaming_bridge_proto_depIdxs = nil
}
