// Copyright (c) 2015-2026 The Decred developers
// Use of this source code is governed by an ISC
// license that can be found in the LICENSE file.

// Storefront theme generator. The dashboard owns a set of generated templates so
// a merchant gets covers + a category grid + per-category pages without editing
// Go templates. simplestore products have no image field and ProcessEmbeds needs
// a literal localfilename in template source, so the SKU->cover mapping is
// emitted into a generated `_cover.tmpl` partial included by index/product.
//
// Generated (refreshed whenever products/covers change): _cover.tmpl, index.tmpl,
// and one <slug>.tmpl per category tag. Written once by "Apply theme":
// header.tmpl (banner) and product.tmpl. Cover convention: covers/<sku>.jpg.

import {
  BisonrelayStoreProduct,
  getBisonrelayStoreTemplates,
  saveBisonrelayStoreTemplate,
} from './bisonrelayApi';

const GEN = '{{/* generated by dcrpulse - edits are overwritten when products or covers change */}}';
const BANNER = '--embed[alt=Storefront,type=image/jpeg,localfilename=banner.jpg]--';
const COVER_TMPL = '_cover.tmpl';

// altText encodes a product-supplied string for an embed `alt=` value. The store
// decodes it with QueryUnescape, so encoding here keeps a title from breaking out
// of the embed directive (e.g. injecting `]--` + another embed).
const altText = (s: string): string => encodeURIComponent(s);

// tmplText neutralizes markdown/template/embed metacharacters in product strings
// that are placed RAW into generated template source (section headings, static
// category cards). Defense in depth: the backend also validates title/tags.
const tmplText = (s: string): string =>
  s
    .replace(/--embed/gi, '')
    .replace(/--form/gi, '')
    .replace(/[{}[\]`]/g, '')
    .trim();

export const categorySlug = (tag: string): string =>
  tag.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'category';

const distinctTags = (products: BisonrelayStoreProduct[]): string[] => {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const p of products) {
    for (const t of p.tags ?? []) {
      if (t && !seen.has(t)) {
        seen.add(t);
        out.push(t);
      }
    }
  }
  return out;
};

const coverEmbed = (p: BisonrelayStoreProduct): string =>
  `--embed[alt=${altText(p.title)},type=image/jpeg,localfilename=covers/${p.sku}.jpg]--`;

// _cover.tmpl: a {{define "cover"}} that emits the matching product's cover embed.
// Used by index.tmpl (per ranged product) and product.tmpl (the page's product).
const buildCoverTmpl = (products: BisonrelayStoreProduct[]): string => {
  const arms = products
    .map((p) => `{{ if eq .SKU "${p.sku}" }}${coverEmbed(p)}{{ end }}`)
    .join('');
  return `${GEN}\n{{ define "cover" }}${arms}{{ end }}\n`;
};

// index.tmpl: banner header, then one --grid-- section per category tag, ranging
// the live product list so new products appear without regeneration of layout.
const buildIndexTmpl = (products: BisonrelayStoreProduct[]): string => {
  const sections = distinctTags(products)
    .map((tag) => {
      const card = [
        `{{ template "cover" $p }}`,
        `**[{{ $p.Title }}](product/{{ $p.SKU }})**`,
        `{{ printf "$%.2f USD" $p.Price }}`,
      ].join('\n');
      const loop =
        `{{ range $p := .Products }}{{ range $p.Tags }}{{ if eq . ${JSON.stringify(tag)} }}\n` +
        `${card}\n` +
        `{{ end }}{{ end }}{{ end }}`;
      return `\n# ${tmplText(tag)}\n\n[see category ->](static/${categorySlug(tag)})\n\n--grid--\n${loop}\n--/grid--\n`;
    })
    .join('');
  return `${GEN}\n{{ template "header.tmpl" . }}\n${sections}\n{{ template "footer.tmpl" . }}\n`;
};

// <slug>.tmpl: a focused category page served via simplestore's static route
// (static/<slug> -> <slug>.tmpl, executed with nil data), so its cards are
// hardcoded (no {{template "cover"}} which would need product data).
const buildCategoryTmpl = (tag: string, products: BisonrelayStoreProduct[]): string => {
  const cards = products
    .filter((p) => (p.tags ?? []).includes(tag))
    .map(
      (p) =>
        `${coverEmbed(p)}\n**[${tmplText(p.title)}](product/${p.sku})**\n$${(p.price || 0).toFixed(2)} USD\n`,
    )
    .join('\n');
  return (
    `${GEN}\n${BANNER}\n\n# ${tmplText(tag)}\n\n--grid--\n${cards}\n--/grid--\n\n` +
    `[<- Back to all categories](/)  [Cart](/cart)  [Orders](/orders)\n`
  );
};

const buildHeaderTmpl = (): string =>
  `${GEN}\n{{ define "header.tmpl" }}\n${BANNER}\n{{ if .IsAdmin -}}\n[Admin Area](/admin)\n{{ end -}}\n{{ end }}\n`;

const buildProductTmpl = (): string =>
  `${GEN}\n# {{ .Title }}\n\n{{ template "cover" . }}\n\n` +
  `Category: {{ range .Tags }}{{ . }} {{ end }}\n\n{{ .Description }}\n\n` +
  `Price: {{ printf "$%.2f USD" .Price }}\n\n---\n## Add to Cart\n--form--\n` +
  `type="action" value="/addToCart"\ntype="hidden" name="sku" value="{{.SKU}}"\n` +
  `type="intinput" label="Quantity" name="qty" value="1"\ntype="submit" label="Add To Cart"\n` +
  `--/form--\n---\n\n[Back to the index](/)  [Cart](/cart)  [Orders](/orders)\n`;

// isThemeManaged reports whether the generated theme is installed (presence of
// _cover.tmpl). When false, the dashboard leaves the merchant's own templates
// alone and does not auto-regenerate on product changes.
export const isThemeManaged = async (): Promise<boolean> => {
  const tmpls = await getBisonrelayStoreTemplates();
  return tmpls.some((t) => t.name === COVER_TMPL);
};

// regenerateThemeContent rewrites the generated set (cover partial, index and
// every category page) from the current product list. Each save is a root-file
// write, which triggers the store's live reload so ProcessEmbeds re-inlines any
// new/removed covers.
const regenerateThemeContent = async (products: BisonrelayStoreProduct[]): Promise<void> => {
  await saveBisonrelayStoreTemplate(COVER_TMPL, buildCoverTmpl(products));
  await saveBisonrelayStoreTemplate('index.tmpl', buildIndexTmpl(products));
  for (const tag of distinctTags(products)) {
    await saveBisonrelayStoreTemplate(`${categorySlug(tag)}.tmpl`, buildCategoryTmpl(tag, products));
  }
};

// refreshTheme regenerates the managed layout if (and only if) the theme is
// installed; safe to call after any product or cover change.
export const refreshTheme = async (products: BisonrelayStoreProduct[]): Promise<void> => {
  if (await isThemeManaged()) {
    await regenerateThemeContent(products);
  }
};

// applyStoreTheme installs the full themed layout, including the one-time
// header (banner) and product templates, and the generated layout set.
export const applyStoreTheme = async (products: BisonrelayStoreProduct[]): Promise<void> => {
  await saveBisonrelayStoreTemplate('header.tmpl', buildHeaderTmpl());
  await saveBisonrelayStoreTemplate('product.tmpl', buildProductTmpl());
  await regenerateThemeContent(products);
};
